// poly_mul C-ABI Known-Answer Test.
//
// Vector source: kinet/crypto/poly_mul Go reference. Same Cyclone-FFT prime
// (Q = 998244353 = 119*2^23 + 1) and same primitive root. KAT pins three
// (n, sA, sB, sum, first, last) tuples generated by the LCG used in the Go
// poly_mul_test.go file -- byte-changes here require a lockstep change there.

#include "crypto.h"
#include "ntt.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {

using kinet::crypto::ntt::Q;
using kinet::crypto::ntt::PRIMITIVE_ROOT;

// Same LCG as poly_mul_test.go (Go math/rand-compatible knuth seq).
std::vector<uint64_t> lcg(uint64_t seed, std::size_t n) {
    std::vector<uint64_t> out(n);
    uint64_t state = seed;
    for (std::size_t i = 0; i < n; ++i) {
        state = state * 6364136223846793005ULL + 1442695040888963407ULL;
        out[i] = state % Q;
    }
    return out;
}

struct Vec {
    const char* name;
    std::size_t n;
    uint64_t    sA, sB;
    uint64_t    sum, first, last;
};

// KATs from kinet/crypto/poly_mul Go reference. Values copied from
// poly_mul/test/vectors/poly_mul_kat.json (the Go-side generator's pinned
// output) so any drift from the Go canonical breaks this test.
const Vec kKATs[] = {
    {"n2",   2,    1,    2,    567996115, 371012399, 196983716},
    {"n8",   8,    1234, 5678, 48246169,  673146415, 767542882},
    {"n32",  32,   7,    13,   72828809,  392054258, 84461645},
    {"n64",  64,   11,   17,   933631914, 967956798, 522099145},
};

}  // namespace

int main() {
    int fail = 0;
    for (const auto& v : kKATs) {
        auto a = lcg(v.sA, v.n);
        auto b = lcg(v.sB, v.n);
        std::vector<uint64_t> c(v.n, 0);

        int rc = poly_mul(a.data(), b.data(), v.n, Q, PRIMITIVE_ROOT, c.data());
        if (rc != CRYPTO_OK) {
            std::fprintf(stderr, "FAIL %s: poly_mul rc=%d\n", v.name, rc);
            ++fail;
            continue;
        }

        uint64_t sum = 0;
        for (uint64_t x : c) {
            if (x >= Q) {
                std::fprintf(stderr, "FAIL %s: out-of-range %llu\n",
                             v.name, (unsigned long long)x);
                ++fail;
            }
            sum = (sum + x) % Q;
        }
        if (sum != v.sum || c.front() != v.first || c.back() != v.last) {
            std::fprintf(stderr,
                         "FAIL %s: got sum=%llu first=%llu last=%llu\n"
                         "             want sum=%llu first=%llu last=%llu\n",
                         v.name,
                         (unsigned long long)sum,
                         (unsigned long long)c.front(),
                         (unsigned long long)c.back(),
                         (unsigned long long)v.sum,
                         (unsigned long long)v.first,
                         (unsigned long long)v.last);
            ++fail;
        } else {
            std::printf("ok   %s\n", v.name);
        }
    }

    // Negative: bad modulus -> CRYPTO_ERR_INPUT.
    uint64_t a = 1, b = 1, c = 0;
    int rc = poly_mul(&a, &b, 1, 17, PRIMITIVE_ROOT, &c);
    if (rc != CRYPTO_ERR_INPUT) {
        std::fprintf(stderr, "FAIL bad-modulus expected INPUT got %d\n", rc);
        ++fail;
    } else {
        std::printf("ok   bad-modulus rejected\n");
    }

    std::printf("\npoly_mul: %d KATs, %d failed\n", (int)(sizeof kKATs / sizeof kKATs[0]) + 1, fail);
    return fail == 0 ? 0 : 1;
}
