// Copyright (c) 2024-2026 Kinet Industries Inc.
// SPDX-License-Identifier: BSD-3-Clause-Eco
//
// Build-time oracle for G2 = E'(Fp2) operations on BLS12-381.
// Emits vectors_g2.h with input + expected-output bytes for the Metal test.
//
// Operations covered:
//   p2_jac_add     : random Jacobian P + random Jacobian Q  (P != Q)
//   p2_jac_dbl     : 2 * Jacobian P
//   p2_mixed_add   : Jacobian P + affine Q
//   p2_scalar_mult : scalar * generator-multiple, output AFFINE for stable bytes
//
// Affine output for scalar mult is the canonical representation; blst's w=5
// Booth-recoded mult and a binary double-and-add converge to the same affine
// point but to different Jacobian X/Y/Z triples, so we compare in affine.

#include <blst.h>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

namespace
{
constexpr int N_G2_OPS    = 100;
constexpr int N_SCALARMUL = 50;

std::mt19937_64 rng{0xDEAD'F00D'CAFEULL};

blst_fp random_fp()
{
    std::array<uint8_t, 48> raw{};
    for (auto& b : raw) b = static_cast<uint8_t>(rng() & 0xFF);
    raw[47] &= 0x1F;          // <p ; modulus is 381 bits
    blst_fp out;
    blst_fp_from_lendian(&out, raw.data());
    return out;
}

blst_fp2 random_fp2() { return blst_fp2{ random_fp(), random_fp() }; }

// Random valid G2 point: scalar * generator. blst_p2_mult takes a 32-byte
// scalar and we mask to a non-trivial value.
blst_p2 random_g2()
{
    std::array<uint8_t, 32> sk{};
    for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
    sk[31] &= 0x3F;           // keep < r (group order, 255 bits)
    sk[0]  |= 0x01;           // ensure nonzero

    const blst_p2* g = blst_p2_generator();
    blst_p2 out;
    blst_p2_mult(&out, g, sk.data(), 256);
    return out;
}

std::string hexdump(const void* p, size_t n)
{
    static const char* hex = "0123456789ABCDEF";
    std::string out;
    out.reserve(n * 4);
    const uint8_t* b = static_cast<const uint8_t*>(p);
    for (size_t i = 0; i < n; i++) {
        if (i > 0 && (i & 0xF) == 0) out += "\n        ";
        out += "0x";
        out += hex[b[i] >> 4];
        out += hex[b[i] & 0xF];
        if (i + 1 < n) out += ", ";
    }
    return out;
}

void emit_bytes(FILE* f, const char* name, const void* data, size_t bytes)
{
    fprintf(f, "static const uint8_t %s[%zu] = {\n        ", name, bytes);
    fputs(hexdump(data, bytes).c_str(), f);
    fputs("\n};\n", f);
}

}  // namespace

int main(int argc, char** argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output_header_path>\n", argv[0]);
        return 1;
    }
    FILE* f = std::fopen(argv[1], "w");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }

    fprintf(f,
        "// Auto-generated by bls_g2_oracle. DO NOT EDIT.\n"
        "// blst is the build-time reference; this header captures its byte\n"
        "// output for byte-equality checking against bls_g2.metal kernels.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "constexpr size_t kG2N           = %d;\n"
        "constexpr size_t kG2ScalarN     = %d;\n"
        "constexpr size_t kP2Bytes       = %zu;\n"
        "constexpr size_t kP2AffBytes    = %zu;\n"
        "constexpr size_t kG2ScalarBits  = 256;\n"
        "\n"
        "// Per-element layout for k_p2_scalar_mult input:\n"
        "//   [0..%zu)  : P2 base    (Jacobian, 288 bytes)\n"
        "//   [%zu..%zu): scalar     (32 bytes, little-endian)\n"
        "constexpr size_t kG2ScalarInBytes = %zu;\n\n",
        N_G2_OPS, N_SCALARMUL,
        sizeof(blst_p2), sizeof(blst_p2_affine),
        sizeof(blst_p2), sizeof(blst_p2),
        sizeof(blst_p2) + 32, sizeof(blst_p2) + 32);

    // ---------------------------------------------------------------
    // p2_jac_add :  random valid points P, Q (different group elements)
    // ---------------------------------------------------------------
    {
        std::vector<blst_p2> A(N_G2_OPS), B(N_G2_OPS), R(N_G2_OPS);
        for (int i = 0; i < N_G2_OPS; i++) {
            A[i] = random_g2();
            do { B[i] = random_g2(); } while (
                std::memcmp(&A[i], &B[i], sizeof(blst_p2)) == 0);
            blst_p2_add(&R[i], &A[i], &B[i]);
        }
        emit_bytes(f, "kG2AddA",    A.data(), sizeof(blst_p2)*N_G2_OPS);
        emit_bytes(f, "kG2AddB",    B.data(), sizeof(blst_p2)*N_G2_OPS);
        emit_bytes(f, "kG2AddOut",  R.data(), sizeof(blst_p2)*N_G2_OPS);
    }

    // ---------------------------------------------------------------
    // p2_jac_dbl :  2 * P
    // ---------------------------------------------------------------
    {
        std::vector<blst_p2> A(N_G2_OPS), R(N_G2_OPS);
        for (int i = 0; i < N_G2_OPS; i++) {
            A[i] = random_g2();
            blst_p2_double(&R[i], &A[i]);
        }
        emit_bytes(f, "kG2DblIn",  A.data(), sizeof(blst_p2)*N_G2_OPS);
        emit_bytes(f, "kG2DblOut", R.data(), sizeof(blst_p2)*N_G2_OPS);
    }

    // ---------------------------------------------------------------
    // p2_mixed_add :  Jacobian P + affine Q
    // ---------------------------------------------------------------
    {
        std::vector<blst_p2>        A(N_G2_OPS);
        std::vector<blst_p2_affine> Baff(N_G2_OPS);
        std::vector<blst_p2>        R(N_G2_OPS);
        for (int i = 0; i < N_G2_OPS; i++) {
            A[i] = random_g2();
            blst_p2 q = random_g2();
            while (std::memcmp(&A[i], &q, sizeof(blst_p2)) == 0) {
                q = random_g2();
            }
            blst_p2_to_affine(&Baff[i], &q);
            blst_p2_add_affine(&R[i], &A[i], &Baff[i]);
        }
        emit_bytes(f, "kG2MixedA",   A.data(),    sizeof(blst_p2)*N_G2_OPS);
        emit_bytes(f, "kG2MixedB",   Baff.data(), sizeof(blst_p2_affine)*N_G2_OPS);
        emit_bytes(f, "kG2MixedOut", R.data(),    sizeof(blst_p2)*N_G2_OPS);
    }

    // ---------------------------------------------------------------
    // p2_scalar_mult :  random base * random 32-byte scalar
    //   Input layout: P2 base (288 B) || scalar (32 B)  per element
    //   Output:       P2Aff (192 B)                      per element
    // ---------------------------------------------------------------
    {
        std::vector<uint8_t> in_data(N_SCALARMUL * (sizeof(blst_p2) + 32));
        std::vector<blst_p2_affine> out_aff(N_SCALARMUL);
        for (int i = 0; i < N_SCALARMUL; i++) {
            blst_p2 base = random_g2();
            std::array<uint8_t, 32> sk{};
            for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
            // Keep all 256 bits in play.
            uint8_t* slot = in_data.data() + i*(sizeof(blst_p2) + 32);
            std::memcpy(slot, &base, sizeof(blst_p2));
            std::memcpy(slot + sizeof(blst_p2), sk.data(), 32);

            blst_p2 result;
            blst_p2_mult(&result, &base, sk.data(), 256);
            blst_p2_to_affine(&out_aff[i], &result);
        }
        emit_bytes(f, "kG2ScalarIn",  in_data.data(),
                   in_data.size());
        emit_bytes(f, "kG2ScalarOut", out_aff.data(),
                   sizeof(blst_p2_affine)*N_SCALARMUL);
    }

    fclose(f);
    fprintf(stderr, "wrote %s\n", argv[1]);
    return 0;
}
