// Copyright (c) 2024-2026 Kinet Industries Inc.
// SPDX-License-Identifier: BSD-3-Clause-Eco
//
// Build-time oracle: generates Fp/Fp2/Fp6/Fp12 test vectors using blst as the
// reference implementation, then writes a C header the Metal-side test suite
// can link against.
//
// blst is the build-time tool here. The production Metal library does not
// link against blst; only this test oracle does.
//
// 100 random vectors per operation × ~7 operations per field × 3 fields ≈ 700+ vectors.
//
// Layout matches blst exactly: blst_fp = 6×64-bit limbs in Montgomery form.
// Both blst and Metal use the same modulus, p0, and limb endianness, so the
// generated bytes can be passed verbatim to Metal kernels and verbatim compared.

#include <blst.h>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

namespace
{
constexpr int N_VECTORS = 100;

// Deterministic generator (seeded) so vector header is reproducible.
std::mt19937_64 rng{0xC0FFEE'BAD'BEEFULL};

// Fill 48 bytes uniformly then reduce mod p (via blst_fp_from_lendian which
// accepts any 48-byte LE bigint and reduces).
blst_fp random_fp()
{
    std::array<uint8_t, 48> raw{};
    for (auto& b : raw) b = static_cast<uint8_t>(rng() & 0xFF);
    // Top bits clipped to keep value < p (blst_fp_from_bendian/lendian does NOT
    // reduce; it requires input < p). 381-bit modulus, so clear top 3 bits.
    raw[47] &= 0x1F;

    blst_fp out;
    blst_fp_from_lendian(&out, raw.data());
    return out;
}

blst_fp2 random_fp2() { return blst_fp2{ random_fp(), random_fp() }; }
blst_fp6 random_fp6() { return blst_fp6{ { random_fp2(), random_fp2(), random_fp2() } }; }
blst_fp12 random_fp12() { return blst_fp12{ { random_fp6(), random_fp6() } }; }

// Hex-dump a byte buffer.
std::string hexdump(const void* p, size_t n)
{
    static const char* hex = "0123456789ABCDEF";
    std::string out;
    out.reserve(n * 4);
    const uint8_t* b = static_cast<const uint8_t*>(p);
    for (size_t i = 0; i < n; i++) {
        if (i > 0 && (i & 0xF) == 0) out += "\n        ";
        out += "0x";
        out += hex[b[i] >> 4];
        out += hex[b[i] & 0xF];
        if (i + 1 < n) out += ", ";
    }
    return out;
}

// Emit a `static const uint8_t name[N] = { ... };` initializer.
void emit_bytes(FILE* f, const char* name, const void* data, size_t bytes)
{
    fprintf(f, "static const uint8_t %s[%zu] = {\n        ", name, bytes);
    fputs(hexdump(data, bytes).c_str(), f);
    fputs("\n};\n", f);
}

// blst's negation; the public API doesn't expose blst_fp2_neg, so we use cneg(flag=true).
void blst_fp2_neg(blst_fp2* r, const blst_fp2* a)
{
    blst_fp2_cneg(r, a, true);
}

// blst's Fp2 conjugation: (a + b u) -> (a - b u). Implement as componentwise.
void blst_fp2_conj(blst_fp2* r, const blst_fp2* a)
{
    r->fp[0] = a->fp[0];
    blst_fp_cneg(&r->fp[1], &a->fp[1], true);
}

}  // namespace

int main(int argc, char** argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output_header_path>\n", argv[0]);
        return 1;
    }
    FILE* f = std::fopen(argv[1], "w");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }

    fprintf(f,
        "// Auto-generated by bls_fp_tower_oracle. DO NOT EDIT.\n"
        "// blst is invoked at build time; this header captures its output bytes\n"
        "// (Montgomery form, 6x64-bit limbs LE) for byte-equality comparison\n"
        "// against the Metal kernels in bls_fp{2,6,12}.metal.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "constexpr size_t kNVectors = %d;\n"
        "constexpr size_t kFp2Bytes  = %zu;\n"
        "constexpr size_t kFp6Bytes  = %zu;\n"
        "constexpr size_t kFp12Bytes = %zu;\n"
        "\n",
        N_VECTORS,
        sizeof(blst_fp2), sizeof(blst_fp6), sizeof(blst_fp12));

    // ------------------------------------------------------------------
    // Fp inversion diagnostic — separate path to localize fp_inv issues.
    // ------------------------------------------------------------------
    fprintf(f, "// Fp inversion diagnostic: input is Fp2 with c0=value c1=0,\n"
               "// expected output is fp_inv(c0) in c0, c1=0.\n");
    {
        std::vector<blst_fp2> in(N_VECTORS), expected(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            blst_fp x = random_fp();
            in[i].fp[0] = x;
            std::memset(&in[i].fp[1], 0, sizeof(blst_fp));
            blst_fp_inverse(&expected[i].fp[0], &x);
            std::memset(&expected[i].fp[1], 0, sizeof(blst_fp));
        }
        emit_bytes(f, "kFpInvIn_bytes",  in.data(),       sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFpInvOut_bytes", expected.data(), sizeof(blst_fp2) * N_VECTORS);
    }

    // ------------------------------------------------------------------
    // Fp2 vectors
    // ------------------------------------------------------------------
    fprintf(f, "// Fp2 inputs (paired): a[i], b[i]\n");
    {
        std::vector<blst_fp2> a(N_VECTORS), b(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            a[i] = random_fp2();
            b[i] = random_fp2();
            // Ensure inv input is non-zero.
            if (i == 0) memset(&a[i], 0, sizeof(a[i])), a[i].fp[0].l[0] = 1;
        }
        emit_bytes(f, "kFp2A_bytes", a.data(), sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2B_bytes", b.data(), sizeof(blst_fp2) * N_VECTORS);

        std::vector<blst_fp2> add(N_VECTORS), sub(N_VECTORS), mul(N_VECTORS),
            sqr(N_VECTORS), inv(N_VECTORS), conj(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            blst_fp2_add(&add[i], &a[i], &b[i]);
            blst_fp2_sub(&sub[i], &a[i], &b[i]);
            blst_fp2_mul(&mul[i], &a[i], &b[i]);
            blst_fp2_sqr(&sqr[i], &a[i]);
            // Skip inv if a[i] is zero (very unlikely with random; we forced i==0 nonzero).
            blst_fp2_inverse(&inv[i], &a[i]);
            blst_fp2_conj(&conj[i], &a[i]);
        }
        emit_bytes(f, "kFp2Add_bytes",  add.data(),  sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2Sub_bytes",  sub.data(),  sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2Mul_bytes",  mul.data(),  sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2Sqr_bytes",  sqr.data(),  sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2Inv_bytes",  inv.data(),  sizeof(blst_fp2) * N_VECTORS);
        emit_bytes(f, "kFp2Conj_bytes", conj.data(), sizeof(blst_fp2) * N_VECTORS);
    }

    // ------------------------------------------------------------------
    // Fp6 vectors. blst doesn't expose Fp6 ops publicly, so we exercise
    // Fp6 indirectly through Fp12 (the Fp12 oracle covers all Fp6 paths).
    // We still emit Fp6 random-input data + the EXPECTED output bytes from
    // *self-test*: by computing  fp12_mul(diag(a, 0), diag(b, 0)) the bottom
    // Fp6 result equals fp6_mul(a, b). This way blst is the oracle for Fp6.
    // ------------------------------------------------------------------
    fprintf(f, "// Fp6 inputs: a[i], b[i]\n");
    {
        std::vector<blst_fp6> a(N_VECTORS), b(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            a[i] = random_fp6();
            b[i] = random_fp6();
        }
        emit_bytes(f, "kFp6A_bytes", a.data(), sizeof(blst_fp6) * N_VECTORS);
        emit_bytes(f, "kFp6B_bytes", b.data(), sizeof(blst_fp6) * N_VECTORS);

        // For Fp6 add/sub the result is just componentwise Fp2 add/sub.
        // We reproduce the byte layout by running blst_fp2_add 3 times.
        std::vector<blst_fp6> add(N_VECTORS), sub(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            for (int k = 0; k < 3; k++) {
                blst_fp2_add(&add[i].fp2[k], &a[i].fp2[k], &b[i].fp2[k]);
                blst_fp2_sub(&sub[i].fp2[k], &a[i].fp2[k], &b[i].fp2[k]);
            }
        }
        emit_bytes(f, "kFp6Add_bytes", add.data(), sizeof(blst_fp6) * N_VECTORS);
        emit_bytes(f, "kFp6Sub_bytes", sub.data(), sizeof(blst_fp6) * N_VECTORS);

        // Fp6 mul/sqr/inv: we compute via Fp12 wrap.
        // For mul: build A = a + 0 w (Fp12), B = b + 0 w (Fp12).
        //   A * B = (a*b) + (a*0 + 0*b) w  =>  A*B.c0 = a*b in Fp6.
        // For sqr: same trick A^2.c0 = a^2.
        // For inv: A^(-1) on A = a + 0 w  has  A^(-1) = a^(-1) + 0 w  iff a is invertible
        //          (since A^(-1) = (a0 - a1 w) / (a0^2 - a1^2 v) and a1=0).
        std::vector<blst_fp6> mul(N_VECTORS), sqr(N_VECTORS), inv(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            blst_fp12 A{}, B{}, R{};
            A.fp6[0] = a[i];
            B.fp6[0] = b[i];
            blst_fp12_mul(&R, &A, &B);
            mul[i] = R.fp6[0];

            blst_fp12_sqr(&R, &A);
            sqr[i] = R.fp6[0];

            blst_fp12_inverse(&R, &A);
            inv[i] = R.fp6[0];
        }
        emit_bytes(f, "kFp6Mul_bytes", mul.data(), sizeof(blst_fp6) * N_VECTORS);
        emit_bytes(f, "kFp6Sqr_bytes", sqr.data(), sizeof(blst_fp6) * N_VECTORS);
        emit_bytes(f, "kFp6Inv_bytes", inv.data(), sizeof(blst_fp6) * N_VECTORS);
    }

    // ------------------------------------------------------------------
    // Fp12 vectors
    // ------------------------------------------------------------------
    fprintf(f, "// Fp12 inputs: a[i], b[i]\n");
    {
        std::vector<blst_fp12> a(N_VECTORS), b(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            a[i] = random_fp12();
            b[i] = random_fp12();
        }
        emit_bytes(f, "kFp12A_bytes", a.data(), sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12B_bytes", b.data(), sizeof(blst_fp12) * N_VECTORS);

        std::vector<blst_fp12> add(N_VECTORS), sub(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            // Fp12 add/sub = componentwise Fp6 add/sub = componentwise Fp2 add/sub.
            for (int j = 0; j < 2; j++) {
                for (int k = 0; k < 3; k++) {
                    blst_fp2_add(&add[i].fp6[j].fp2[k],
                                 &a[i].fp6[j].fp2[k], &b[i].fp6[j].fp2[k]);
                    blst_fp2_sub(&sub[i].fp6[j].fp2[k],
                                 &a[i].fp6[j].fp2[k], &b[i].fp6[j].fp2[k]);
                }
            }
        }
        emit_bytes(f, "kFp12Add_bytes", add.data(), sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12Sub_bytes", sub.data(), sizeof(blst_fp12) * N_VECTORS);

        std::vector<blst_fp12> mul(N_VECTORS), sqr(N_VECTORS), inv(N_VECTORS),
            conj(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            blst_fp12_mul(&mul[i], &a[i], &b[i]);
            blst_fp12_sqr(&sqr[i], &a[i]);
            blst_fp12_inverse(&inv[i], &a[i]);
            conj[i] = a[i];
            blst_fp12_conjugate(&conj[i]);
        }
        emit_bytes(f, "kFp12Mul_bytes",  mul.data(),  sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12Sqr_bytes",  sqr.data(),  sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12Inv_bytes",  inv.data(),  sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12Conj_bytes", conj.data(), sizeof(blst_fp12) * N_VECTORS);

        // Cyclotomic squaring is only defined for cyclotomic-subgroup elements.
        // We construct cyclotomic elements by: take a random g != 0 in Fp12,
        // raise to ((p^6 - 1)*(p^2 + 1)) — the easy part of final exponentiation.
        // But that's expensive; instead we use blst's pairing to produce one,
        // since e(P, Q) is in the cyclotomic subgroup. We reuse `a[i]` raised
        // through blst_fp12_conjugate * blst_fp12_inverse to produce an element
        // of the form g^(p^6 - 1), which lies in the cyclotomic subgroup.
        std::vector<blst_fp12> cyclo_in(N_VECTORS), cyclo_out(N_VECTORS);
        for (int i = 0; i < N_VECTORS; i++) {
            // g_easy = a^(p^6 - 1) = conj(a) * a^(-1)
            blst_fp12 inv_a, conj_a, g_easy;
            blst_fp12_inverse(&inv_a, &a[i]);
            conj_a = a[i];
            blst_fp12_conjugate(&conj_a);
            blst_fp12_mul(&g_easy, &conj_a, &inv_a);
            cyclo_in[i] = g_easy;
            blst_fp12_cyclotomic_sqr(&cyclo_out[i], &g_easy);
        }
        emit_bytes(f, "kFp12CycloIn_bytes",  cyclo_in.data(),
                   sizeof(blst_fp12) * N_VECTORS);
        emit_bytes(f, "kFp12CycloOut_bytes", cyclo_out.data(),
                   sizeof(blst_fp12) * N_VECTORS);
    }

    fclose(f);
    fprintf(stderr, "wrote %s\n", argv[1]);
    return 0;
}
