// Copyright (c) 2024-2026 Kinet Industries Inc.
// SPDX-License-Identifier: BSD-3-Clause-Eco
//
// Build-time oracle for the BLS12-381 optimal-ate Miller loop.
// Emits vectors_miller.h with 100 random (P, Q) inputs and the matching
// blst_miller_loop output (576-byte Fp12 each), pre-final-exponentiation.

#include <blst.h>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

namespace
{
constexpr int N_MILLER = 100;

std::mt19937_64 rng{0xFEED'FACEULL};

blst_p1 random_g1()
{
    std::array<uint8_t, 32> sk{};
    for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
    sk[31] &= 0x3F;
    sk[0]  |= 0x01;
    blst_p1 out;
    blst_p1_mult(&out, blst_p1_generator(), sk.data(), 256);
    return out;
}

blst_p2 random_g2()
{
    std::array<uint8_t, 32> sk{};
    for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
    sk[31] &= 0x3F;
    sk[0]  |= 0x01;
    blst_p2 out;
    blst_p2_mult(&out, blst_p2_generator(), sk.data(), 256);
    return out;
}

std::string hexdump(const void* p, size_t n)
{
    static const char* hex = "0123456789ABCDEF";
    std::string out;
    out.reserve(n * 4);
    const uint8_t* b = static_cast<const uint8_t*>(p);
    for (size_t i = 0; i < n; i++) {
        if (i > 0 && (i & 0xF) == 0) out += "\n        ";
        out += "0x";
        out += hex[b[i] >> 4];
        out += hex[b[i] & 0xF];
        if (i + 1 < n) out += ", ";
    }
    return out;
}

void emit_bytes(FILE* f, const char* name, const void* data, size_t bytes)
{
    fprintf(f, "static const uint8_t %s[%zu] = {\n        ", name, bytes);
    fputs(hexdump(data, bytes).c_str(), f);
    fputs("\n};\n", f);
}

}  // namespace

int main(int argc, char** argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output_header_path>\n", argv[0]);
        return 1;
    }
    FILE* f = std::fopen(argv[1], "w");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }

    fprintf(f,
        "// Auto-generated by bls_miller_oracle. DO NOT EDIT.\n"
        "// blst_miller_loop output bytes for byte-equality testing of\n"
        "// bls_miller.metal (pre-final-exponentiation Fp12 result).\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "constexpr size_t kMillerN          = %d;\n"
        "constexpr size_t kMillerInBytes    = %zu;   // P2Aff (192) + P1Aff (96)\n"
        "constexpr size_t kMillerOutBytes   = %zu;   // Fp12\n"
        "\n",
        N_MILLER,
        sizeof(blst_p2_affine) + sizeof(blst_p1_affine),
        sizeof(blst_fp12));

    std::vector<uint8_t>   in_data(N_MILLER * (sizeof(blst_p2_affine)
                                               + sizeof(blst_p1_affine)));
    std::vector<blst_fp12> out_data(N_MILLER);

    for (int i = 0; i < N_MILLER; i++) {
        blst_p1 P_jac = random_g1();
        blst_p2 Q_jac = random_g2();

        blst_p1_affine P_aff;
        blst_p2_affine Q_aff;
        blst_p1_to_affine(&P_aff, &P_jac);
        blst_p2_to_affine(&Q_aff, &Q_jac);

        // Layout per element: Q_aff || P_aff
        uint8_t* slot = in_data.data()
                      + i * (sizeof(blst_p2_affine) + sizeof(blst_p1_affine));
        std::memcpy(slot, &Q_aff, sizeof(blst_p2_affine));
        std::memcpy(slot + sizeof(blst_p2_affine), &P_aff,
                    sizeof(blst_p1_affine));

        blst_miller_loop(&out_data[i], &Q_aff, &P_aff);
    }

    emit_bytes(f, "kMillerIn",  in_data.data(),  in_data.size());
    emit_bytes(f, "kMillerOut", out_data.data(),
               sizeof(blst_fp12) * N_MILLER);

    fclose(f);
    fprintf(stderr, "wrote %s\n", argv[1]);
    return 0;
}
