// Copyright (c) 2024-2026 Kinet Industries Inc.
// SPDX-License-Identifier: BSD-3-Clause-Eco
//
// Build-time oracle for BLS12-381 final exponentiation.
// Emits vectors_final_exp.h with 100 random Fp12 inputs (in cyclotomic-friendly
// form, i.e. obtained via blst_miller_loop on random (P, Q) pairs so they are
// valid pre-final-exp values) and the matching blst_final_exp output.

#include <blst.h>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

namespace
{
constexpr int N_FE = 100;

std::mt19937_64 rng{0xCAFE'D00DULL};

blst_p1 random_g1()
{
    std::array<uint8_t, 32> sk{};
    for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
    sk[31] &= 0x3F;
    sk[0]  |= 0x01;
    blst_p1 out;
    blst_p1_mult(&out, blst_p1_generator(), sk.data(), 256);
    return out;
}

blst_p2 random_g2()
{
    std::array<uint8_t, 32> sk{};
    for (auto& b : sk) b = static_cast<uint8_t>(rng() & 0xFF);
    sk[31] &= 0x3F;
    sk[0]  |= 0x01;
    blst_p2 out;
    blst_p2_mult(&out, blst_p2_generator(), sk.data(), 256);
    return out;
}

std::string hexdump(const void* p, size_t n)
{
    static const char* hex = "0123456789ABCDEF";
    std::string out;
    out.reserve(n * 4);
    const uint8_t* b = static_cast<const uint8_t*>(p);
    for (size_t i = 0; i < n; i++) {
        if (i > 0 && (i & 0xF) == 0) out += "\n        ";
        out += "0x";
        out += hex[b[i] >> 4];
        out += hex[b[i] & 0xF];
        if (i + 1 < n) out += ", ";
    }
    return out;
}

void emit_bytes(FILE* f, const char* name, const void* data, size_t bytes)
{
    fprintf(f, "static const uint8_t %s[%zu] = {\n        ", name, bytes);
    fputs(hexdump(data, bytes).c_str(), f);
    fputs("\n};\n", f);
}

}  // namespace

int main(int argc, char** argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output_header_path>\n", argv[0]);
        return 1;
    }
    FILE* f = std::fopen(argv[1], "w");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }

    fprintf(f,
        "// Auto-generated by bls_final_exp_oracle. DO NOT EDIT.\n"
        "// blst_final_exp output bytes for byte-equality testing of\n"
        "// bls_final_exp.metal.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "constexpr size_t kFEN          = %d;\n"
        "constexpr size_t kFEBytes      = %zu;   // Fp12\n"
        "\n",
        N_FE,
        sizeof(blst_fp12));

    std::vector<blst_fp12> in_data(N_FE);
    std::vector<blst_fp12> out_data(N_FE);

    for (int i = 0; i < N_FE; i++) {
        blst_p1 P_jac = random_g1();
        blst_p2 Q_jac = random_g2();

        blst_p1_affine P_aff;
        blst_p2_affine Q_aff;
        blst_p1_to_affine(&P_aff, &P_jac);
        blst_p2_to_affine(&Q_aff, &Q_jac);

        // Generate cyclotomic-friendly Fp12 values via Miller loop, then run
        // final_exp on each. This matches the actual production input domain
        // (final_exp is only called on Miller-loop outputs).
        blst_miller_loop(&in_data[i], &Q_aff, &P_aff);
        blst_final_exp(&out_data[i], &in_data[i]);
    }

    emit_bytes(f, "kFEIn",  in_data.data(),  sizeof(blst_fp12) * N_FE);
    emit_bytes(f, "kFEOut", out_data.data(), sizeof(blst_fp12) * N_FE);

    fclose(f);
    fprintf(stderr, "wrote %s\n", argv[1]);
    return 0;
}
