// SPDX-License-Identifier: Apache-2.0
//
// gen_element_kat.go -- emit Banderwagon group-element KAT vectors for the
// C++ implementation in kinet-labs/crypto/banderwagon. Source of truth is
// github.com/kinet-labs/crypto/ipa/banderwagon (which wraps gnark-crypto
// bls12-381/bandersnatch).
//
// Usage:
//   cd /Users/z/work/kinet-labs/crypto/banderwagon/test/tools
//   go run gen_element_kat.go > ../element_kat.h
//
// Produces:
//   - 16 valid encodings: round-trippable [s] = scalar*generator for
//     deterministic scalars (compressed form, 32 bytes BE).
//   - 16 bad-subgroup-rejection cases: x-coordinates that produce a valid
//     point on Bandersnatch but fail the (1 - a*x^2) Legendre check.
package main

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"os"

	gnarkbander "github.com/consensys/gnark-crypto/ecc/bls12-381/bandersnatch"
	gnarkfp "github.com/consensys/gnark-crypto/ecc/bls12-381/fr"
	"github.com/kinet-labs/crypto/ipa/banderwagon"
	"github.com/kinet-labs/crypto/ipa/bandersnatch"
	"github.com/kinet-labs/crypto/ipa/bandersnatch/fp"
	"github.com/kinet-labs/crypto/ipa/bandersnatch/fr"
)

// 32-byte big-endian print of an fp.Element (canonical Bytes()).
func feBytesBE(e *fp.Element) [32]byte {
	return e.Bytes()
}

func cBytes32(b [32]byte) string {
	out := ""
	for i, x := range b {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("0x%02x", x)
	}
	return out
}

// xorshift64* -- deterministic PRG matching gen_fp_kat.go.
type detRng struct{ s uint64 }

func newDetRng(seed uint64) *detRng { return &detRng{s: seed} }
func (r *detRng) next() uint64 {
	x := r.s
	x ^= x << 13
	x ^= x >> 7
	x ^= x << 17
	r.s = x
	return x * 2685821657736338717
}

func randScalarLT(r *detRng) fr.Element {
	for {
		var buf [32]byte
		for i := 0; i < 4; i++ {
			v := r.next()
			buf[8*i+0] = byte(v)
			buf[8*i+1] = byte(v >> 8)
			buf[8*i+2] = byte(v >> 16)
			buf[8*i+3] = byte(v >> 24)
			buf[8*i+4] = byte(v >> 32)
			buf[8*i+5] = byte(v >> 40)
			buf[8*i+6] = byte(v >> 48)
			buf[8*i+7] = byte(v >> 56)
		}
		buf[31] &= 0x07 // ensure well below r
		e, err := gnarkfp.LittleEndian.Element(&buf)
		if err != nil {
			continue
		}
		_ = e
		// Build a canonical fr.Element from the bytes.
		var f fr.Element
		f.SetBytesLE(buf[:])
		return f
	}
}

func main() {
	out := os.Stdout

	// --- Encoding KATs: scalar*generator round-trip, byte-equal Go reference.
	encodingScalars := []*big.Int{
		big.NewInt(1),
		big.NewInt(2),
		big.NewInt(3),
		big.NewInt(7),
		big.NewInt(123456789),
		// Plus 11 deterministic pseudo-randoms.
	}
	prng := newDetRng(0xb1ff_b1ff_b1ff_b1ff)
	for len(encodingScalars) < 16 {
		fe := randScalarLT(prng)
		var bi big.Int
		fe.ToBigIntRegular(&bi)
		// Skip zero (would map to identity, which has a special encoding).
		if bi.Sign() == 0 {
			continue
		}
		encodingScalars = append(encodingScalars, &bi)
	}

	type encKat struct {
		name string
		s    [32]byte // scalar (LE, canonical)
		enc  [32]byte // compressed encoding (BE)
	}
	var encs []encKat
	for i, s := range encodingScalars {
		var p banderwagon.Element
		p = banderwagon.Generator
		var sFr fr.Element
		sFr.SetBigInt(s)
		p.ScalarMul(&p, &sFr)
		encBytes := p.Bytes()
		var sLE [32]byte
		// LE canonical encoding of scalar (32-byte little-endian).
		sCanon := s.Bytes() // big-endian
		// Pad/copy to LE.
		for j := 0; j < len(sCanon); j++ {
			sLE[j] = sCanon[len(sCanon)-1-j]
		}
		encs = append(encs, encKat{
			name: fmt.Sprintf("enc_s%d", i),
			s:    sLE,
			enc:  encBytes,
		})
	}

	// --- Bad-subgroup-rejection KATs: 16 x-coordinates that decode to a
	// curve point but where (1 - a*x^2) is a non-residue, so subgroup_check
	// rejects.  Generated by sampling random x in Fp and keeping those with
	// Legendre(1 - a*x^2) == -1 *and* (a*x^2 - 1)/(d*x^2 - 1) is a QR (so it
	// IS on Bandersnatch -- otherwise the rejection would be by on-curve
	// check, not subgroup check).
	type badKat struct {
		name string
		enc  [32]byte
	}
	var bads []badKat
	{
		// Quick helper: check whether (1 - a*x^2) is a non-residue and y exists.
		probe := newDetRng(0xbad_5ec0_face_50ff)
		idx := 0
		attempts := 0
		for len(bads) < 16 && attempts < 100000 {
			attempts++
			// sample x
			var xb [32]byte
			for i := 0; i < 4; i++ {
				v := probe.next()
				xb[8*i+0] = byte(v)
				xb[8*i+1] = byte(v >> 8)
				xb[8*i+2] = byte(v >> 16)
				xb[8*i+3] = byte(v >> 24)
				xb[8*i+4] = byte(v >> 32)
				xb[8*i+5] = byte(v >> 40)
				xb[8*i+6] = byte(v >> 48)
				xb[8*i+7] = byte(v >> 56)
			}
			xb[31] &= 0x3f
			var x fp.Element
			x.SetBytes(xb[:])

			// y^2 = (a*x^2 - 1) / (d*x^2 - 1)
			var x2, num, den, y2 fp.Element
			x2.Square(&x)
			one := fp.One()
			cp := gnarkbander.GetEdwardsCurve()
			cpA := cp.A
			cpD := cp.D
			num.Mul(&x2, &cpA)
			num.Sub(&num, &one)
			den.Mul(&x2, &cpD)
			den.Sub(&den, &one)
			if den.IsZero() {
				continue
			}
			y2.Div(&num, &den)
			// Need y to exist (so it's on the curve)...
			y := fp.SqrtPrecomp(&y2)
			if y == nil {
				continue
			}
			// ...and (1 - a*x^2) to be a non-residue (so subgroup check fails).
			var oneMinusAx2 fp.Element
			oneMinusAx2.Mul(&x2, &cpA)
			oneMinusAx2.Sub(&one, &oneMinusAx2)
			if oneMinusAx2.Legendre() > 0 {
				continue
			}

			// Found one. Encode the x-coordinate as if for compressed Banderwagon.
			// Use the convention from banderwagon.Element.Bytes(): if y is not
			// lex-largest, negate x. We don't actually have a Banderwagon point
			// (it fails subgroup), but we want bytes that the C++ decoder will
			// process and (correctly) reject.
			affineX := x
			if !y.LexicographicallyLargest() {
				affineX.Neg(&affineX)
			}
			enc := affineX.Bytes()
			bads = append(bads, badKat{
				name: fmt.Sprintf("bad_subgroup_%d", idx),
				enc:  enc,
			})
			idx++
		}
		_ = bandersnatch.Identity
	}

	// --- Emit C++ header ------------------------------------------------------
	fmt.Fprintln(out, "// SPDX-License-Identifier: Apache-2.0")
	fmt.Fprintln(out, "// element_kat.h -- generated by banderwagon/test/tools/gen_element_kat.go")
	fmt.Fprintln(out, "// Source: github.com/kinet-labs/crypto/ipa/banderwagon (gnark-crypto wrapper).")
	fmt.Fprintln(out, "// DO NOT EDIT.")
	fmt.Fprintln(out, "#pragma once")
	fmt.Fprintln(out, "#include <cstdint>")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "namespace kinet::banderwagon::kat {")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "struct ElementEncKat {")
	fmt.Fprintln(out, "    const char* name;")
	fmt.Fprintln(out, "    std::uint8_t scalar_le[32]; // scalar s, 32-byte LE canonical")
	fmt.Fprintln(out, "    std::uint8_t enc_be[32];    // compressed encoding of [s]G, 32-byte BE")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "struct ElementBadKat {")
	fmt.Fprintln(out, "    const char* name;")
	fmt.Fprintln(out, "    std::uint8_t enc_be[32]; // 32-byte BE encoding that must be rejected")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintf(out, "constexpr int kElementEncKatCount = %d;\n", len(encs))
	fmt.Fprintf(out, "constexpr int kElementBadKatCount = %d;\n", len(bads))
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "inline const ElementEncKat kElementEncKats[] = {")
	for _, k := range encs {
		fmt.Fprintf(out, "    {\"%s\",\n", k.name)
		fmt.Fprintf(out, "     {%s},\n", cBytes32(k.s))
		fmt.Fprintf(out, "     {%s}},\n", cBytes32(k.enc))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "inline const ElementBadKat kElementBadKats[] = {")
	for _, k := range bads {
		fmt.Fprintf(out, "    {\"%s\",\n", k.name)
		fmt.Fprintf(out, "     {%s}},\n", cBytes32(k.enc))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "}  // namespace kinet::banderwagon::kat")

	// silence unused
	_ = rand.Reader
	_ = bandersnatch.Identity
	_ = feBytesBE
}
