// Codegen for the Banderwagon GPU constant tables (Metal, CUDA, WGSL). One
// invocation, three outputs -- the CPU body's internal accessors are the only
// producer, so drift between CPU and any GPU backend is structurally
// impossible. Same generator pattern as poseidon_gen_gpu_constants.
//
// Usage:
//   banderwagon_gen_gpu_constants <metalh-out> <cuh-out> <wgslh-out>
//
// Each output path may be passed as "/dev/null" to skip that backend.

#include "../../cpp/fp.hpp"
#include "../../cpp/fr.hpp"
#include "../../cpp/element.hpp"

#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstring>

using kinet::banderwagon::Fp;
using kinet::banderwagon::Fr;
using kinet::banderwagon::Element;
using kinet::banderwagon::curve_a;
using kinet::banderwagon::curve_d;

namespace kinet::banderwagon::internal {
void fp_modulus(std::uint64_t out[4]);
void fp_r_squared(std::uint64_t out[4]);
void fp_r_mod_q(std::uint64_t out[4]);
std::uint64_t fp_qinv_neg();

void fr_modulus(std::uint64_t out[4]);
void fr_r_squared(std::uint64_t out[4]);
void fr_r_mod_r(std::uint64_t out[4]);
std::uint64_t fr_rinv_neg();
}  // namespace kinet::banderwagon::internal

namespace {

struct Const4 { const char* name; std::uint64_t v[4]; };
struct Const1 { const char* name; std::uint64_t v;    };

void gather(Const4 fours[10], Const1 ones[2]) {
    int idx = 0;
    fours[idx].name = "FP_Q";
    kinet::banderwagon::internal::fp_modulus(fours[idx].v);
    ++idx;
    fours[idx].name = "FP_R2";
    kinet::banderwagon::internal::fp_r_squared(fours[idx].v);
    ++idx;
    fours[idx].name = "FP_R";
    kinet::banderwagon::internal::fp_r_mod_q(fours[idx].v);
    ++idx;
    fours[idx].name = "FR_R_MOD";
    kinet::banderwagon::internal::fr_modulus(fours[idx].v);
    ++idx;
    fours[idx].name = "FR_R2";
    kinet::banderwagon::internal::fr_r_squared(fours[idx].v);
    ++idx;
    fours[idx].name = "FR_R";
    kinet::banderwagon::internal::fr_r_mod_r(fours[idx].v);
    ++idx;
    Fp a = curve_a();
    fours[idx].name = "CURVE_A";
    fours[idx].v[0] = a.limbs[0]; fours[idx].v[1] = a.limbs[1];
    fours[idx].v[2] = a.limbs[2]; fours[idx].v[3] = a.limbs[3];
    ++idx;
    Fp d = curve_d();
    fours[idx].name = "CURVE_D";
    fours[idx].v[0] = d.limbs[0]; fours[idx].v[1] = d.limbs[1];
    fours[idx].v[2] = d.limbs[2]; fours[idx].v[3] = d.limbs[3];
    ++idx;
    Element g = Element::generator();
    fours[idx].name = "GEN_X";
    fours[idx].v[0] = g.X.limbs[0]; fours[idx].v[1] = g.X.limbs[1];
    fours[idx].v[2] = g.X.limbs[2]; fours[idx].v[3] = g.X.limbs[3];
    ++idx;
    fours[idx].name = "GEN_Y";
    fours[idx].v[0] = g.Y.limbs[0]; fours[idx].v[1] = g.Y.limbs[1];
    fours[idx].v[2] = g.Y.limbs[2]; fours[idx].v[3] = g.Y.limbs[3];
    ++idx;

    ones[0].name = "FP_QINV_NEG";
    ones[0].v    = kinet::banderwagon::internal::fp_qinv_neg();
    ones[1].name = "FR_QINV_NEG";
    ones[1].v    = kinet::banderwagon::internal::fr_rinv_neg();
}

const char kProvenance[] =
    "// Source: banderwagon/cpp/{fp,fr,element}.cpp via internal accessors.\n"
    "// Single producer of the GPU constant table -- the CPU body is the\n"
    "// source of truth. Any drift fails the determinism test by construction.\n";

bool emit_metal(const char* path, const Const4 fours[10], const Const1 ones[2]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) { std::fprintf(stderr, "cannot open %s\n", path); return false; }
    std::fprintf(fp,
        "// Auto-generated by banderwagon_gen_gpu_constants (Metal). Do not edit.\n"
        "%s"
        "#ifndef KINET_BANDERWAGON_CONST_METALH\n"
        "#define KINET_BANDERWAGON_CONST_METALH\n\n",
        kProvenance);
    for (int i = 0; i < 10; ++i) {
        for (int j = 0; j < 4; ++j) {
            std::fprintf(fp, "constant ulong %s_%d = 0x%016" PRIx64 "UL;\n",
                fours[i].name, j, fours[i].v[j]);
        }
        std::fprintf(fp, "\n");
    }
    for (int i = 0; i < 2; ++i) {
        std::fprintf(fp, "constant ulong %s = 0x%016" PRIx64 "UL;\n",
            ones[i].name, ones[i].v);
    }
    std::fprintf(fp, "\n#endif  // KINET_BANDERWAGON_CONST_METALH\n");
    std::fclose(fp);
    return true;
}

bool emit_cuda(const char* path, const Const4 fours[10], const Const1 ones[2]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) { std::fprintf(stderr, "cannot open %s\n", path); return false; }
    std::fprintf(fp,
        "// Auto-generated by banderwagon_gen_gpu_constants (CUDA). Do not edit.\n"
        "%s"
        "#ifndef KINET_BANDERWAGON_CONST_CUH\n"
        "#define KINET_BANDERWAGON_CONST_CUH\n"
        "\n"
        "#if defined(__CUDA_ARCH__)\n"
        "#  define KINET_BANDERWAGON_CUDA_DEV __device__\n"
        "#else\n"
        "#  define KINET_BANDERWAGON_CUDA_DEV\n"
        "#endif\n\n",
        kProvenance);
    for (int i = 0; i < 10; ++i) {
        for (int j = 0; j < 4; ++j) {
            std::fprintf(fp,
                "static KINET_BANDERWAGON_CUDA_DEV const unsigned long long "
                "%s_%d = 0x%016" PRIx64 "ULL;\n",
                fours[i].name, j, fours[i].v[j]);
        }
        std::fprintf(fp, "\n");
    }
    for (int i = 0; i < 2; ++i) {
        std::fprintf(fp,
            "static KINET_BANDERWAGON_CUDA_DEV const unsigned long long "
            "%s = 0x%016" PRIx64 "ULL;\n",
            ones[i].name, ones[i].v);
    }
    std::fprintf(fp, "\n#endif  // KINET_BANDERWAGON_CONST_CUH\n");
    std::fclose(fp);
    return true;
}

bool emit_wgsl(const char* path, const Const4 fours[10], const Const1 ones[2]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) { std::fprintf(stderr, "cannot open %s\n", path); return false; }
    std::fprintf(fp,
        "// Auto-generated by banderwagon_gen_gpu_constants (WGSL). Do not edit.\n"
        "%s"
        "// WGSL has no u64; each 64-bit constant is split into a (lo, hi) pair\n"
        "// of u32. This file is a polyglot header consumed by both the WGSL\n"
        "// kernel (textual prefix prepended at compile time) and the C++ host\n"
        "// polyfill driver (#include).\n"
        "#ifndef KINET_BANDERWAGON_CONST_WGSLH\n"
        "#define KINET_BANDERWAGON_CONST_WGSLH\n"
        "\n"
        "#ifdef __cplusplus\n"
        "#include <cstdint>\n",
        kProvenance);
    for (int i = 0; i < 10; ++i) {
        for (int j = 0; j < 4; ++j) {
            std::uint32_t lo = (std::uint32_t)(fours[i].v[j] & 0xFFFFFFFFu);
            std::uint32_t hi = (std::uint32_t)(fours[i].v[j] >> 32);
            std::fprintf(fp,
                "static const uint32_t %s_%d_LO = 0x%08" PRIx32 "u;\n"
                "static const uint32_t %s_%d_HI = 0x%08" PRIx32 "u;\n",
                fours[i].name, j, lo, fours[i].name, j, hi);
        }
        std::fprintf(fp, "\n");
    }
    for (int i = 0; i < 2; ++i) {
        std::uint32_t lo = (std::uint32_t)(ones[i].v & 0xFFFFFFFFu);
        std::uint32_t hi = (std::uint32_t)(ones[i].v >> 32);
        std::fprintf(fp,
            "static const uint32_t %s_LO = 0x%08" PRIx32 "u;\n"
            "static const uint32_t %s_HI = 0x%08" PRIx32 "u;\n",
            ones[i].name, lo, ones[i].name, hi);
    }
    std::fprintf(fp, "\n#else  // not __cplusplus -> WGSL\n\n");
    for (int i = 0; i < 10; ++i) {
        for (int j = 0; j < 4; ++j) {
            std::uint32_t lo = (std::uint32_t)(fours[i].v[j] & 0xFFFFFFFFu);
            std::uint32_t hi = (std::uint32_t)(fours[i].v[j] >> 32);
            std::fprintf(fp,
                "const %s_%d_LO : u32 = 0x%08" PRIx32 "u;\n"
                "const %s_%d_HI : u32 = 0x%08" PRIx32 "u;\n",
                fours[i].name, j, lo, fours[i].name, j, hi);
        }
        std::fprintf(fp, "\n");
    }
    for (int i = 0; i < 2; ++i) {
        std::uint32_t lo = (std::uint32_t)(ones[i].v & 0xFFFFFFFFu);
        std::uint32_t hi = (std::uint32_t)(ones[i].v >> 32);
        std::fprintf(fp,
            "const %s_LO : u32 = 0x%08" PRIx32 "u;\n"
            "const %s_HI : u32 = 0x%08" PRIx32 "u;\n",
            ones[i].name, lo, ones[i].name, hi);
    }
    std::fprintf(fp, "\n#endif  // __cplusplus\n");
    std::fprintf(fp, "\n#endif  // KINET_BANDERWAGON_CONST_WGSLH\n");
    std::fclose(fp);
    return true;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr,
            "usage: %s <metalh-out> <cuh-out> <wgslh-out>\n", argv[0]);
        return 2;
    }
    Const4 fours[10];
    Const1 ones[2];
    gather(fours, ones);
    if (!emit_metal(argv[1], fours, ones)) return 1;
    if (!emit_cuda (argv[2], fours, ones)) return 1;
    if (!emit_wgsl (argv[3], fours, ones)) return 1;
    return 0;
}
