// SPDX-License-Identifier: Apache-2.0
//
// gen_fr_kat.go -- emit Bandersnatch scalar-field (Fr) KAT vectors for the
// C++ implementation in kinet-labs/crypto/banderwagon.
//
// Usage:
//   cd /Users/z/work/kinet-labs/crypto/banderwagon/test/tools
//   go run gen_fr_kat.go > ../fr_kat.h
//
// The reference is github.com/kinet-labs/crypto/ipa/bandersnatch/fr (the same
// 253-bit Bandersnatch scalar field also produced by gnark-crypto's
// internal generator under bls12-381/bandersnatch). All bytes are
// little-endian canonical 32-byte encodings (BytesLE / SetBytesLECanonical).
package main

import (
	"encoding/hex"
	"fmt"
	"os"

	"github.com/kinet-labs/crypto/ipa/bandersnatch/fr"
)

func leBytes(e fr.Element) [32]byte {
	return e.BytesLE()
}

func cBytes(b [32]byte) string {
	out := ""
	for i, x := range b {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("0x%02x", x)
	}
	return out
}

func main() {
	addCases := []struct {
		name   string
		seedAB [2]string
	}{
		{"add_0_1", [2]string{"00", "01"}},
		{"add_neg1_1", [2]string{"qm1", "01"}},
		{"add_qhalf_qhalf", [2]string{"qhalf", "qhalf"}},
		{"add_rand_a", [2]string{"rand1a", "rand1b"}},
		{"add_rand_b", [2]string{"rand2a", "rand2b"}},
	}
	mulCases := []struct {
		name   string
		seedAB [2]string
	}{
		{"mul_0_x", [2]string{"00", "rand1a"}},
		{"mul_1_x", [2]string{"01", "rand1b"}},
		{"mul_2_2", [2]string{"02", "02"}},
		{"mul_rand_a", [2]string{"rand2a", "rand2b"}},
		{"mul_rand_b", [2]string{"rand3a", "rand3b"}},
	}

	bag := map[string]fr.Element{}
	bag["00"] = fr.Zero()
	bag["01"] = fr.One()
	{
		var two fr.Element
		two.SetUint64(2)
		bag["02"] = two
	}
	{
		var qm1 fr.Element
		one := fr.One()
		qm1.Neg(&one) // -1 mod q == q - 1
		bag["qm1"] = qm1
	}
	{
		// (q-1)/2 in the field: just compute as -1 / 2
		var qhalf, two fr.Element
		two.SetUint64(2)
		one := fr.One()
		var qm1 fr.Element
		qm1.Neg(&one)
		qhalf.Div(&qm1, &two)
		bag["qhalf"] = qhalf
	}
	prng := newDetRng(0xa5a5_a5a5_a5a5_a5a5)
	for _, k := range []string{"rand1a", "rand1b", "rand2a", "rand2b", "rand3a", "rand3b"} {
		bag[k] = randLT(prng)
	}

	type kat struct {
		name    string
		op      string
		a, b, r [32]byte
	}
	var kats []kat
	for _, c := range addCases {
		a := bag[c.seedAB[0]]
		b := bag[c.seedAB[1]]
		var r fr.Element
		r.Add(&a, &b)
		kats = append(kats, kat{c.name, "add", leBytes(a), leBytes(b), leBytes(r)})
	}
	for _, c := range mulCases {
		a := bag[c.seedAB[0]]
		b := bag[c.seedAB[1]]
		var r fr.Element
		r.Mul(&a, &b)
		kats = append(kats, kat{c.name, "mul", leBytes(a), leBytes(b), leBytes(r)})
	}

	out := os.Stdout
	fmt.Fprintln(out, "// SPDX-License-Identifier: Apache-2.0")
	fmt.Fprintln(out, "// fr_kat.h -- generated by banderwagon/test/tools/gen_fr_kat.go")
	fmt.Fprintln(out, "// Source: github.com/kinet-labs/crypto/ipa/bandersnatch/fr (253-bit scalar field).")
	fmt.Fprintln(out, "// DO NOT EDIT.")
	fmt.Fprintln(out, "#pragma once")
	fmt.Fprintln(out, "#include <cstdint>")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "namespace kinet::banderwagon::kat {")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "struct FrKat {")
	fmt.Fprintln(out, "    const char* name;")
	fmt.Fprintln(out, "    const char* op;     // \"add\" or \"mul\"")
	fmt.Fprintln(out, "    std::uint8_t a[32];")
	fmt.Fprintln(out, "    std::uint8_t b[32];")
	fmt.Fprintln(out, "    std::uint8_t r[32];")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintf(out, "constexpr int kFrKatCount = %d;\n", len(kats))
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "inline const FrKat kFrKats[] = {")
	for _, k := range kats {
		fmt.Fprintf(out, "    {\"%s\", \"%s\",\n", k.name, k.op)
		fmt.Fprintf(out, "     {%s},\n", cBytes(k.a))
		fmt.Fprintf(out, "     {%s},\n", cBytes(k.b))
		fmt.Fprintf(out, "     {%s}},\n", cBytes(k.r))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "}  // namespace kinet::banderwagon::kat")

	_ = hex.EncodeToString
}

// --- deterministic RNG ----------------------------------------------------

type detRng struct{ s uint64 }

func newDetRng(seed uint64) *detRng { return &detRng{s: seed} }

func (r *detRng) next() uint64 {
	// xorshift64*
	x := r.s
	x ^= x << 13
	x ^= x >> 7
	x ^= x << 17
	r.s = x
	return x * 2685821657736338717
}

func randLT(r *detRng) fr.Element {
	for {
		var buf [32]byte
		for i := 0; i < 4; i++ {
			v := r.next()
			buf[8*i+0] = byte(v)
			buf[8*i+1] = byte(v >> 8)
			buf[8*i+2] = byte(v >> 16)
			buf[8*i+3] = byte(v >> 24)
			buf[8*i+4] = byte(v >> 32)
			buf[8*i+5] = byte(v >> 40)
			buf[8*i+6] = byte(v >> 48)
			buf[8*i+7] = byte(v >> 56)
		}
		// Mask top 3 bits so candidate < 2^253 < q.
		// q ~= 2^253 (its top hex nybble is 1).
		buf[31] &= 0x1f
		// SetBytesLECanonical mutates input -- pass a copy.
		cp := make([]byte, 32)
		copy(cp, buf[:])
		var e fr.Element
		if _, err := e.SetBytesLECanonical(cp); err != nil {
			continue
		}
		return e
	}
}
