# Concatenates the Banderwagon WGSL kernel source and the auto-generated
# constants header into banderwagon_wgsl_sources.h, embedded by the host
# driver as raw string literals.

file(READ "${KERNEL}"    _BW_KERNEL)
file(READ "${CONSTANTS}" _BW_CONST)

file(WRITE "${OUTPUT}"
    "// Auto-generated by wrap_wgsl_sources.cmake. Do not edit.\n"
    "#pragma once\n\n"
    "static constexpr char kBANDERWAGON_WGSL_Constants[] = R\"BWCONST(\n"
    "${_BW_CONST}\n"
    ")BWCONST\";\n\n"
    "static constexpr char kBANDERWAGON_WGSL_Kernel[] = R\"BWKERN(\n"
    "${_BW_KERNEL}\n"
    ")BWKERN\";\n")
