// WGSL driver for Banderwagon group ops -- C++ host polyfill of the WGSL
// kernel.
//
// Mirrors banderwagon/gpu/wgsl/banderwagon.wgsl byte-for-byte: each 64-bit
// Montgomery limb is represented as a (lo, hi) pair of uint32_t, and every
// 64-bit op is reconstructed from u32 primitives. This is exactly what WGSL
// does; running the same arithmetic on the host gives byte-equal output to
// both the WGSL kernel and the CPU oracle.
//
// The constant table comes from banderwagon_const.wgslh (auto-generated by
// the CPU body via banderwagon_gen_gpu_constants), which is a polyglot header
// emitting both __cplusplus `static const uint32_t` arrays and WGSL `const`
// declarations.

#include "banderwagon_driver.h"
#include "banderwagon_const.wgslh"

#include <cstdint>
#include <cstring>

namespace {

struct U64 { uint32_t lo, hi; };

inline U64 u64_zero() { return U64{0u, 0u}; }
inline bool u64_lt(U64 a, U64 b) {
    if (a.hi != b.hi) return a.hi < b.hi;
    return a.lo < b.lo;
}
inline bool u64_eq(U64 a, U64 b) { return a.lo == b.lo && a.hi == b.hi; }

struct U64Carry  { U64 v; uint32_t carry;  };
struct U64Borrow { U64 v; uint32_t borrow; };

inline U64Carry u64_add_carry(U64 a, U64 b, uint32_t cin) {
    uint32_t lo1 = a.lo + b.lo;
    uint32_t c0  = (lo1 < a.lo) ? 1u : 0u;
    uint32_t lo  = lo1 + cin;
    uint32_t c1  = (lo  < lo1) ? 1u : 0u;
    uint32_t hi1 = a.hi + b.hi;
    uint32_t c2  = (hi1 < a.hi) ? 1u : 0u;
    uint32_t hi2 = hi1 + (c0 + c1);
    uint32_t c3  = (hi2 < hi1) ? 1u : 0u;
    return U64Carry{U64{lo, hi2}, c2 + c3};
}

inline U64Borrow u64_sub_borrow(U64 a, U64 b, uint32_t bin) {
    uint32_t lo1  = a.lo - b.lo;
    uint32_t bor0 = (a.lo < b.lo) ? 1u : 0u;
    uint32_t lo   = lo1 - bin;
    uint32_t bor1 = (lo1 < bin)   ? 1u : 0u;
    uint32_t hi1  = a.hi - b.hi;
    uint32_t bor2 = (a.hi < b.hi) ? 1u : 0u;
    uint32_t bor_in_hi = bor0 + bor1;
    uint32_t hi   = hi1 - bor_in_hi;
    uint32_t bor3 = (hi1 < bor_in_hi) ? 1u : 0u;
    return U64Borrow{U64{lo, hi}, bor2 + bor3};
}

inline U64 u32_mul64(uint32_t a, uint32_t b) {
    uint32_t al = a & 0xffffu;
    uint32_t ah = a >> 16;
    uint32_t bl = b & 0xffffu;
    uint32_t bh = b >> 16;
    uint32_t ll = al * bl;
    uint32_t lh = al * bh;
    uint32_t hl = ah * bl;
    uint32_t hh = ah * bh;
    uint32_t mid_a = (ll >> 16) + (lh & 0xffffu);
    uint32_t mid_b = mid_a + (hl & 0xffffu);
    uint32_t mid_carry = (mid_b >> 16);
    uint32_t lo = (ll & 0xffffu) | (mid_b << 16);
    uint32_t hi = hh + (lh >> 16) + (hl >> 16) + mid_carry;
    return U64{lo, hi};
}

struct U128 { uint32_t l0, l1, l2, l3; };

inline U128 umul64(U64 a, U64 b) {
    U64 p_ll = u32_mul64(a.lo, b.lo);
    U64 p_lh = u32_mul64(a.lo, b.hi);
    U64 p_hl = u32_mul64(a.hi, b.lo);
    U64 p_hh = u32_mul64(a.hi, b.hi);
    uint32_t w0 = p_ll.lo;
    uint32_t s1a = p_ll.hi + p_lh.lo;
    uint32_t c1a = (s1a < p_ll.hi) ? 1u : 0u;
    uint32_t w1  = s1a + p_hl.lo;
    uint32_t c1b = (w1  < s1a)     ? 1u : 0u;
    uint32_t carry1 = c1a + c1b;
    uint32_t s2a = p_lh.hi + p_hl.hi;
    uint32_t c2a = (s2a < p_lh.hi) ? 1u : 0u;
    uint32_t s2b = s2a + p_hh.lo;
    uint32_t c2b = (s2b < s2a)     ? 1u : 0u;
    uint32_t w2  = s2b + carry1;
    uint32_t c2c = (w2  < s2b)     ? 1u : 0u;
    uint32_t carry2 = c2a + c2b + c2c;
    uint32_t w3  = p_hh.hi + carry2;
    return U128{w0, w1, w2, w3};
}

inline U64 u64_mul_low(U64 a, U64 b) {
    U64 p_ll = u32_mul64(a.lo, b.lo);
    U64 p_lh = u32_mul64(a.lo, b.hi);
    U64 p_hl = u32_mul64(a.hi, b.lo);
    uint32_t lo = p_ll.lo;
    uint32_t hi = p_ll.hi + p_lh.lo + p_hl.lo;
    return U64{lo, hi};
}

struct Fp { U64 l0, l1, l2, l3; };
struct Pt { Fp X, Y, Z; };

inline Fp fp_zero() { return Fp{u64_zero(), u64_zero(), u64_zero(), u64_zero()}; }

inline Fp fp_q() {
    return Fp{
        U64{FP_Q_0_LO, FP_Q_0_HI}, U64{FP_Q_1_LO, FP_Q_1_HI},
        U64{FP_Q_2_LO, FP_Q_2_HI}, U64{FP_Q_3_LO, FP_Q_3_HI}
    };
}

inline Fp fp_one() {
    return Fp{
        U64{FP_R_0_LO, FP_R_0_HI}, U64{FP_R_1_LO, FP_R_1_HI},
        U64{FP_R_2_LO, FP_R_2_HI}, U64{FP_R_3_LO, FP_R_3_HI}
    };
}

inline Fp fp_curve_a() {
    return Fp{
        U64{CURVE_A_0_LO, CURVE_A_0_HI}, U64{CURVE_A_1_LO, CURVE_A_1_HI},
        U64{CURVE_A_2_LO, CURVE_A_2_HI}, U64{CURVE_A_3_LO, CURVE_A_3_HI}
    };
}

inline Fp fp_curve_d() {
    return Fp{
        U64{CURVE_D_0_LO, CURVE_D_0_HI}, U64{CURVE_D_1_LO, CURVE_D_1_HI},
        U64{CURVE_D_2_LO, CURVE_D_2_HI}, U64{CURVE_D_3_LO, CURVE_D_3_HI}
    };
}

inline U64 fp_qinv() { return U64{FP_QINV_NEG_LO, FP_QINV_NEG_HI}; }

inline Fp fp_cond_sub_q(const Fp &a) {
    Fp q = fp_q();
    auto r0 = u64_sub_borrow(a.l0, q.l0, 0u);
    auto r1 = u64_sub_borrow(a.l1, q.l1, r0.borrow);
    auto r2 = u64_sub_borrow(a.l2, q.l2, r1.borrow);
    auto r3 = u64_sub_borrow(a.l3, q.l3, r2.borrow);
    uint32_t br = r3.borrow;
    uint32_t mask = (br == 1u) ? 0u : 0xffffffffu;
    return Fp{
        U64{(a.l0.lo & ~mask) | (r0.v.lo & mask),
            (a.l0.hi & ~mask) | (r0.v.hi & mask)},
        U64{(a.l1.lo & ~mask) | (r1.v.lo & mask),
            (a.l1.hi & ~mask) | (r1.v.hi & mask)},
        U64{(a.l2.lo & ~mask) | (r2.v.lo & mask),
            (a.l2.hi & ~mask) | (r2.v.hi & mask)},
        U64{(a.l3.lo & ~mask) | (r3.v.lo & mask),
            (a.l3.hi & ~mask) | (r3.v.hi & mask)},
    };
}

inline Fp fp_cond_add_q(const Fp &a, uint32_t mask) {
    Fp q = fp_q();
    U64 add0{q.l0.lo & mask, q.l0.hi & mask};
    U64 add1{q.l1.lo & mask, q.l1.hi & mask};
    U64 add2{q.l2.lo & mask, q.l2.hi & mask};
    U64 add3{q.l3.lo & mask, q.l3.hi & mask};
    auto r0 = u64_add_carry(a.l0, add0, 0u);
    auto r1 = u64_add_carry(a.l1, add1, r0.carry);
    auto r2 = u64_add_carry(a.l2, add2, r1.carry);
    auto r3 = u64_add_carry(a.l3, add3, r2.carry);
    return Fp{r0.v, r1.v, r2.v, r3.v};
}

inline Fp fp_add(const Fp &a, const Fp &b) {
    auto r0 = u64_add_carry(a.l0, b.l0, 0u);
    auto r1 = u64_add_carry(a.l1, b.l1, r0.carry);
    auto r2 = u64_add_carry(a.l2, b.l2, r1.carry);
    auto r3 = u64_add_carry(a.l3, b.l3, r2.carry);
    return fp_cond_sub_q(Fp{r0.v, r1.v, r2.v, r3.v});
}

inline Fp fp_sub(const Fp &a, const Fp &b) {
    auto r0 = u64_sub_borrow(a.l0, b.l0, 0u);
    auto r1 = u64_sub_borrow(a.l1, b.l1, r0.borrow);
    auto r2 = u64_sub_borrow(a.l2, b.l2, r1.borrow);
    auto r3 = u64_sub_borrow(a.l3, b.l3, r2.borrow);
    uint32_t mask = (r3.borrow == 1u) ? 0xffffffffu : 0u;
    return fp_cond_add_q(Fp{r0.v, r1.v, r2.v, r3.v}, mask);
}

inline Fp fp_mul(const Fp &a, const Fp &b) {
    U64 t[5] = {u64_zero(), u64_zero(), u64_zero(), u64_zero(), u64_zero()};
    const U64 al[4] = {a.l0, a.l1, a.l2, a.l3};
    const U64 bl[4] = {b.l0, b.l1, b.l2, b.l3};
    const U64 qq[4] = {
        U64{FP_Q_0_LO, FP_Q_0_HI}, U64{FP_Q_1_LO, FP_Q_1_HI},
        U64{FP_Q_2_LO, FP_Q_2_HI}, U64{FP_Q_3_LO, FP_Q_3_HI},
    };
    U64 qinv = fp_qinv();

    for (int i = 0; i < 4; ++i) {
        U64 cy = u64_zero();
        for (int j = 0; j < 4; ++j) {
            U128 prod = umul64(al[j], bl[i]);
            U64 lo = U64{prod.l0, prod.l1};
            U64 hi = U64{prod.l2, prod.l3};
            auto s  = u64_add_carry(t[j], lo, 0u);
            auto s2 = u64_add_carry(s.v,  cy, 0u);
            t[j] = s2.v;
            auto cy1 = u64_add_carry(hi,    U64{s.carry,  0u}, 0u);
            auto cy2 = u64_add_carry(cy1.v, U64{s2.carry, 0u}, 0u);
            cy = cy2.v;
        }
        auto t4u = u64_add_carry(t[4], cy, 0u);
        t[4] = t4u.v;
        uint32_t big_carry = t4u.carry;

        U64 m = u64_mul_low(t[0], qinv);

        cy = u64_zero();
        for (int j = 0; j < 4; ++j) {
            U128 prod = umul64(m, qq[j]);
            U64 lo = U64{prod.l0, prod.l1};
            U64 hi = U64{prod.l2, prod.l3};
            auto s  = u64_add_carry(t[j], lo, 0u);
            auto s2 = u64_add_carry(s.v,  cy, 0u);
            t[j] = s2.v;
            auto cy1 = u64_add_carry(hi,    U64{s.carry,  0u}, 0u);
            auto cy2 = u64_add_carry(cy1.v, U64{s2.carry, 0u}, 0u);
            cy = cy2.v;
        }
        auto t3_step = u64_add_carry(t[4], cy, 0u);
        auto t4_step = u64_add_carry(u64_zero(),
                                      U64{big_carry, 0u},
                                      t3_step.carry);
        t[0] = t[1];
        t[1] = t[2];
        t[2] = t[3];
        t[3] = t3_step.v;
        t[4] = t4_step.v;
    }

    Fp r{t[0], t[1], t[2], t[3]};
    if (!(t[4].lo == 0u && t[4].hi == 0u)) {
        auto s0 = u64_sub_borrow(r.l0, U64{FP_Q_0_LO, FP_Q_0_HI}, 0u);
        auto s1 = u64_sub_borrow(r.l1, U64{FP_Q_1_LO, FP_Q_1_HI}, s0.borrow);
        auto s2 = u64_sub_borrow(r.l2, U64{FP_Q_2_LO, FP_Q_2_HI}, s1.borrow);
        auto s3 = u64_sub_borrow(r.l3, U64{FP_Q_3_LO, FP_Q_3_HI}, s2.borrow);
        return Fp{s0.v, s1.v, s2.v, s3.v};
    }
    return fp_cond_sub_q(r);
}

inline Fp fp_square(const Fp &a) { return fp_mul(a, a); }

inline Pt pt_identity() { return Pt{fp_zero(), fp_one(), fp_one()}; }

inline Pt pt_add(const Pt &p1, const Pt &p2) {
    Fp d_const = fp_curve_d();
    Fp a_const = fp_curve_a();

    Fp A = fp_mul(p1.Z, p2.Z);
    Fp B = fp_square(A);
    Fp C = fp_mul(p1.X, p2.X);
    Fp D = fp_mul(p1.Y, p2.Y);
    Fp E = fp_mul(d_const, fp_mul(C, D));
    Fp F = fp_sub(B, E);
    Fp G = fp_add(B, E);
    Fp H = fp_add(p1.X, p1.Y);
    Fp I = fp_add(p2.X, p2.Y);

    Fp t = fp_mul(H, I);
    t = fp_sub(t, C);
    t = fp_sub(t, D);
    t = fp_mul(t, A);
    Fp X3 = fp_mul(t, F);

    Fp aC = fp_mul(a_const, C);
    Fp t2 = fp_sub(D, aC);
    t2 = fp_mul(t2, A);
    Fp Y3 = fp_mul(t2, G);

    Fp Z3 = fp_mul(F, G);
    return Pt{X3, Y3, Z3};
}

inline Pt pt_double(const Pt &p) {
    Fp a_const = fp_curve_a();
    Fp XY = fp_add(p.X, p.Y);
    Fp B  = fp_square(XY);
    Fp C  = fp_square(p.X);
    Fp D  = fp_square(p.Y);
    Fp E  = fp_mul(a_const, C);
    Fp F  = fp_add(E, D);
    Fp H  = fp_square(p.Z);
    Fp twoH = fp_add(H, H);
    Fp J  = fp_sub(F, twoH);

    Fp t = fp_sub(B, C);
    t = fp_sub(t, D);
    Fp X3 = fp_mul(t, J);
    Fp Y3 = fp_mul(F, fp_sub(E, D));
    Fp Z3 = fp_mul(F, J);
    return Pt{X3, Y3, Z3};
}

inline Pt pt_cmov_select(const Pt &dst, const Pt &src, uint32_t mask) {
    auto sel = [mask](U64 a, U64 b) -> U64 {
        return U64{(a.lo & ~mask) | (b.lo & mask),
                   (a.hi & ~mask) | (b.hi & mask)};
    };
    return Pt{
        Fp{sel(dst.X.l0, src.X.l0), sel(dst.X.l1, src.X.l1),
           sel(dst.X.l2, src.X.l2), sel(dst.X.l3, src.X.l3)},
        Fp{sel(dst.Y.l0, src.Y.l0), sel(dst.Y.l1, src.Y.l1),
           sel(dst.Y.l2, src.Y.l2), sel(dst.Y.l3, src.Y.l3)},
        Fp{sel(dst.Z.l0, src.Z.l0), sel(dst.Z.l1, src.Z.l1),
           sel(dst.Z.l2, src.Z.l2), sel(dst.Z.l3, src.Z.l3)},
    };
}

inline Pt pt_scalar_mul(const Pt &p, const std::uint8_t s_le[32]) {
    Pt acc  = pt_identity();
    Pt base = p;
    for (int byte_idx = 0; byte_idx < 32; ++byte_idx) {
        std::uint8_t b = s_le[byte_idx];
        for (int bit = 0; bit < 8; ++bit) {
            uint32_t one_or_zero = (uint32_t)((b >> bit) & 1u);
            uint32_t mask = (one_or_zero == 1u) ? 0xffffffffu : 0u;
            Pt sum = pt_add(acc, base);
            acc = pt_cmov_select(acc, sum, mask);
            base = pt_double(base);
        }
    }
    return acc;
}

inline U64 read_u64_le(const std::uint8_t *p) {
    uint32_t lo = (uint32_t)p[0]
                | ((uint32_t)p[1] << 8)
                | ((uint32_t)p[2] << 16)
                | ((uint32_t)p[3] << 24);
    uint32_t hi = (uint32_t)p[4]
                | ((uint32_t)p[5] << 8)
                | ((uint32_t)p[6] << 16)
                | ((uint32_t)p[7] << 24);
    return U64{lo, hi};
}

inline void write_u64_le(std::uint8_t *p, U64 v) {
    p[0] = (std::uint8_t)(v.lo);
    p[1] = (std::uint8_t)(v.lo >> 8);
    p[2] = (std::uint8_t)(v.lo >> 16);
    p[3] = (std::uint8_t)(v.lo >> 24);
    p[4] = (std::uint8_t)(v.hi);
    p[5] = (std::uint8_t)(v.hi >> 8);
    p[6] = (std::uint8_t)(v.hi >> 16);
    p[7] = (std::uint8_t)(v.hi >> 24);
}

inline Fp read_fp(const std::uint8_t *p) {
    return Fp{read_u64_le(p), read_u64_le(p + 8),
              read_u64_le(p + 16), read_u64_le(p + 24)};
}

inline void write_fp(std::uint8_t *p, const Fp &x) {
    write_u64_le(p,      x.l0);
    write_u64_le(p +  8, x.l1);
    write_u64_le(p + 16, x.l2);
    write_u64_le(p + 24, x.l3);
}

inline Pt read_pt(const std::uint8_t *p) {
    return Pt{read_fp(p), read_fp(p + 32), read_fp(p + 64)};
}

inline void write_pt(std::uint8_t *p, const Pt &v) {
    write_fp(p,      v.X);
    write_fp(p + 32, v.Y);
    write_fp(p + 64, v.Z);
}

}  // namespace

extern "C" int banderwagon_wgsl_add_batch(const std::uint8_t *pairs,
                                          std::uint8_t       *outs,
                                          unsigned long       n) {
    if (n == 0) return 0;
    if (!pairs || !outs) return -1;
    for (unsigned long i = 0; i < n; ++i) {
        Pt P = read_pt(pairs + i * 192);
        Pt Q = read_pt(pairs + i * 192 + 96);
        Pt R = pt_add(P, Q);
        write_pt(outs + i * 96, R);
    }
    return 0;
}

extern "C" int banderwagon_wgsl_double_batch(const std::uint8_t *pts,
                                             std::uint8_t       *outs,
                                             unsigned long       n) {
    if (n == 0) return 0;
    if (!pts || !outs) return -1;
    for (unsigned long i = 0; i < n; ++i) {
        Pt P = read_pt(pts + i * 96);
        Pt R = pt_double(P);
        write_pt(outs + i * 96, R);
    }
    return 0;
}

extern "C" int banderwagon_wgsl_smul_batch(const std::uint8_t *pts,
                                           const std::uint8_t *scalars,
                                           std::uint8_t       *outs,
                                           unsigned long       n) {
    if (n == 0) return 0;
    if (!pts || !scalars || !outs) return -1;
    for (unsigned long i = 0; i < n; ++i) {
        Pt P = read_pt(pts + i * 96);
        Pt R = pt_scalar_mul(P, scalars + i * 32);
        write_pt(outs + i * 96, R);
    }
    return 0;
}

extern "C" int banderwagon_wgsl_msm_batch(const std::uint8_t *pts,
                                          const std::uint8_t *scalars,
                                          std::uint8_t       *outs,
                                          unsigned long       n,
                                          unsigned long       M) {
    if (n == 0 || M == 0) return 0;
    if (!pts || !scalars || !outs) return -1;
    for (unsigned long b = 0; b < M; ++b) {
        Pt acc = pt_identity();
        for (unsigned long i = 0; i < n; ++i) {
            Pt P = read_pt(pts + i * 96);
            Pt term = pt_scalar_mul(P, scalars + (b * n + i) * 32);
            acc = pt_add(acc, term);
        }
        write_pt(outs + b * 96, acc);
    }
    return 0;
}
