// Codegen for the GPU Poseidon2-BN254 round-key constant tables (Metal, CUDA,
// WGSL). Reads round-keys via the CPU body's dump_round_keys (the same code
// path that produces the canonical CPU output), then emits one header per
// backend. This is the *only* producer of GPU round constants -- drift between
// CPU and any GPU backend is structurally impossible.
//
// Layout in every header:
//   POSEIDON2_RK[round][slot][limb]   round = 0..55, slot = 0..1, limb = 0..3
//
// Slot indexing matches dump_round_keys order:
//   round 0..2   : full pre-rounds   (slot 0 and 1 used)
//   round 3..52  : partial rounds    (slot 0 used; slot 1 = 0, ignored by perm)
//   round 53..55 : full post-rounds  (slot 0 and 1 used)
//
// Usage:
//   gen_gpu_constants <metalh-out> <cuh-out> <wgsl-h-out>
//
// Each output path may be omitted by passing "/dev/null"; missing args are
// rejected to keep CMake invocation explicit.

#include "../../cpp/poseidon.hpp"

#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstring>

using kinet::crypto::poseidon::Fr;
using kinet::crypto::poseidon::kTotalRounds;
using kinet::crypto::poseidon::kWidth;
using kinet::crypto::poseidon::internal::dump_round_keys;

namespace {

bool emit_metal(const char* path, const Fr (*keys)[kWidth]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) {
        std::fprintf(stderr, "cannot open %s\n", path);
        return false;
    }
    std::fprintf(fp,
        "// Auto-generated by poseidon_gen_gpu_constants. Do not edit.\n"
        "// Source: poseidon/cpp/poseidon.cpp::dump_round_keys (Keccak-seeded\n"
        "// from \"Poseidon2-BN254[t=2,rF=6,rP=50,d=5]\", gnark-crypto v0.20.1).\n"
        "//\n"
        "// Layout: POSEIDON2_RK[round][slot][limb], slot=0..1, limb=0..3 (LE).\n"
        "#ifndef KINET_POSEIDON2_BN254_RK_METALH\n"
        "#define KINET_POSEIDON2_BN254_RK_METALH\n"
        "\n"
        "constant ulong POSEIDON2_RK[%d][2][4] = {\n",
        kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    {");
        std::fprintf(fp,
            "{0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL}, ",
            keys[r][0].limbs[0], keys[r][0].limbs[1],
            keys[r][0].limbs[2], keys[r][0].limbs[3]);
        std::fprintf(fp,
            "{0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL, 0x%016" PRIx64 "UL}",
            keys[r][1].limbs[0], keys[r][1].limbs[1],
            keys[r][1].limbs[2], keys[r][1].limbs[3]);
        std::fprintf(fp, "}%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, "};\n\n#endif  // KINET_POSEIDON2_BN254_RK_METALH\n");
    std::fclose(fp);
    return true;
}

bool emit_cuda(const char* path, const Fr (*keys)[kWidth]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) {
        std::fprintf(stderr, "cannot open %s\n", path);
        return false;
    }
    std::fprintf(fp,
        "// Auto-generated by poseidon_gen_gpu_constants. Do not edit.\n"
        "// Source: poseidon/cpp/poseidon.cpp::dump_round_keys (Keccak-seeded\n"
        "// from \"Poseidon2-BN254[t=2,rF=6,rP=50,d=5]\", gnark-crypto v0.20.1).\n"
        "#ifndef KINET_POSEIDON2_BN254_RK_CUH\n"
        "#define KINET_POSEIDON2_BN254_RK_CUH\n"
        "\n"
        "// __device__ in CUDA, plain const otherwise (host polyfill).\n"
        "#ifndef __CUDA_ARCH__\n"
        "#define KINET_POSEIDON_CUDA_DEV\n"
        "#else\n"
        "#define KINET_POSEIDON_CUDA_DEV __device__\n"
        "#endif\n"
        "\n"
        "static KINET_POSEIDON_CUDA_DEV const unsigned long long\n"
        "    POSEIDON2_RK[%d][2][4] = {\n",
        kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    {");
        std::fprintf(fp,
            "{0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL}, ",
            keys[r][0].limbs[0], keys[r][0].limbs[1],
            keys[r][0].limbs[2], keys[r][0].limbs[3]);
        std::fprintf(fp,
            "{0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL}",
            keys[r][1].limbs[0], keys[r][1].limbs[1],
            keys[r][1].limbs[2], keys[r][1].limbs[3]);
        std::fprintf(fp, "}%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, "};\n\n#endif  // KINET_POSEIDON2_BN254_RK_CUH\n");
    std::fclose(fp);
    return true;
}

// WGSL has no native u64; we emit each 64-bit limb as two u32 (lo first, hi
// second). The kernel splits Montgomery arithmetic into u32 pieces. Layout:
//   POSEIDON2_RK_LO[round][slot][limb]  -> low  32 bits of each 64-bit limb
//   POSEIDON2_RK_HI[round][slot][limb]  -> high 32 bits of each 64-bit limb
// This keeps all numeric data uniform and lets WGSL build u64 ops as pairs.
bool emit_wgsl(const char* path, const Fr (*keys)[kWidth]) {
    if (!std::strcmp(path, "/dev/null")) return true;
    std::FILE* fp = std::fopen(path, "w");
    if (!fp) {
        std::fprintf(stderr, "cannot open %s\n", path);
        return false;
    }
    std::fprintf(fp,
        "// Auto-generated by poseidon_gen_gpu_constants. Do not edit.\n"
        "// Source: poseidon/cpp/poseidon.cpp::dump_round_keys (Keccak-seeded\n"
        "// from \"Poseidon2-BN254[t=2,rF=6,rP=50,d=5]\", gnark-crypto v0.20.1).\n"
        "//\n"
        "// WGSL has no u64; each 64-bit Montgomery limb is split into a pair\n"
        "// of u32 (lo, hi). The kernel reconstructs u64 ops from u32 pairs.\n"
        "//\n"
        "// This file is intended to be #included into both the WGSL kernel\n"
        "// (as a textual prefix when wgpu compiles the module) and the host\n"
        "// polyfill driver written in C++. The C++ side guards as a header.\n"
        "#ifndef KINET_POSEIDON2_BN254_RK_WGSLH\n"
        "#define KINET_POSEIDON2_BN254_RK_WGSLH\n"
        "\n"
        "#ifdef __cplusplus\n"
        "// Host polyfill (C++): plain `static const` arrays so the WGSL\n"
        "// emulator can read the same numeric data the kernel reads.\n"
        "#include <cstdint>\n"
        "static const uint32_t POSEIDON2_RK_LO[%d][2][4] = {\n",
        kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    {");
        for (int s = 0; s < 2; ++s) {
            std::fprintf(fp, "{");
            for (int j = 0; j < 4; ++j) {
                uint32_t lo = static_cast<uint32_t>(keys[r][s].limbs[j] & 0xFFFFFFFFu);
                std::fprintf(fp, "0x%08" PRIx32 "u%s",
                             lo, j == 3 ? "" : ", ");
            }
            std::fprintf(fp, "}%s", s == 0 ? ", " : "");
        }
        std::fprintf(fp, "}%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, "};\n");
    std::fprintf(fp,
        "static const uint32_t POSEIDON2_RK_HI[%d][2][4] = {\n",
        kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    {");
        for (int s = 0; s < 2; ++s) {
            std::fprintf(fp, "{");
            for (int j = 0; j < 4; ++j) {
                uint32_t hi = static_cast<uint32_t>(keys[r][s].limbs[j] >> 32);
                std::fprintf(fp, "0x%08" PRIx32 "u%s",
                             hi, j == 3 ? "" : ", ");
            }
            std::fprintf(fp, "}%s", s == 0 ? ", " : "");
        }
        std::fprintf(fp, "}%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, "};\n\n#else  // not __cplusplus -> WGSL\n");
    std::fprintf(fp,
        "// WGSL: storage layout matches the host arrays element-by-element.\n"
        "const POSEIDON2_NUM_ROUNDS: u32 = %du;\n",
        kTotalRounds);
    std::fprintf(fp,
        "const POSEIDON2_RK_LO: array<array<array<u32, 4>, 2>, %d> = array<array<array<u32, 4>, 2>, %d>(\n",
        kTotalRounds, kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    array<array<u32, 4>, 2>(");
        for (int s = 0; s < 2; ++s) {
            std::fprintf(fp, "array<u32, 4>(");
            for (int j = 0; j < 4; ++j) {
                uint32_t lo = static_cast<uint32_t>(keys[r][s].limbs[j] & 0xFFFFFFFFu);
                std::fprintf(fp, "0x%08" PRIx32 "u%s",
                             lo, j == 3 ? "" : ", ");
            }
            std::fprintf(fp, ")%s", s == 0 ? ", " : "");
        }
        std::fprintf(fp, ")%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, ");\n");
    std::fprintf(fp,
        "const POSEIDON2_RK_HI: array<array<array<u32, 4>, 2>, %d> = array<array<array<u32, 4>, 2>, %d>(\n",
        kTotalRounds, kTotalRounds);
    for (int r = 0; r < kTotalRounds; ++r) {
        std::fprintf(fp, "    array<array<u32, 4>, 2>(");
        for (int s = 0; s < 2; ++s) {
            std::fprintf(fp, "array<u32, 4>(");
            for (int j = 0; j < 4; ++j) {
                uint32_t hi = static_cast<uint32_t>(keys[r][s].limbs[j] >> 32);
                std::fprintf(fp, "0x%08" PRIx32 "u%s",
                             hi, j == 3 ? "" : ", ");
            }
            std::fprintf(fp, ")%s", s == 0 ? ", " : "");
        }
        std::fprintf(fp, ")%s\n", r + 1 == kTotalRounds ? "" : ",");
    }
    std::fprintf(fp, ");\n\n#endif  // __cplusplus\n");
    std::fprintf(fp, "\n#endif  // KINET_POSEIDON2_BN254_RK_WGSLH\n");
    std::fclose(fp);
    return true;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr,
                     "usage: %s <metalh-out> <cuh-out> <wgslh-out>\n",
                     argv[0]);
        return 2;
    }
    Fr keys[kTotalRounds][kWidth];
    dump_round_keys(keys);
    if (!emit_metal(argv[1], keys)) return 1;
    if (!emit_cuda (argv[2], keys)) return 1;
    if (!emit_wgsl (argv[3], keys)) return 1;
    return 0;
}
