// Auto-generated by bn254_gen_pairing_constants (CUDA). Do not edit.
// Source: bn254/cpp/bn254_pairing.cpp (lines 41-119) via
// bn254_gen_pairing_constants. The CPU body is the single producer of
// these limbs; any drift between CPU and GPU fails the determinism test.
#ifndef KINET_BN254_PAIRING_CONST_CUH
#define KINET_BN254_PAIRING_CONST_CUH

__device__ static const unsigned long long K_NR1P1_A0[4] = {0xaf9ba69633144907ULL, 0xca6b1d7387afb78aULL, 0x11bded5ef08a2087ULL, 0x02f34d751a1f3a7cULL};
__device__ static const unsigned long long K_NR1P1_A1[4] = {0xa222ae234c492d72ULL, 0xd00f02a4565de15bULL, 0xdc2ff3a253dfc926ULL, 0x10a75716b3899551ULL};
__device__ static const unsigned long long K_NR1P2_A0[4] = {0xb5773b104563ab30ULL, 0x347f91c8a9aa6454ULL, 0x7a007127242e0991ULL, 0x1956bcd8118214ecULL};
__device__ static const unsigned long long K_NR1P2_A1[4] = {0x6e849f1ea0aa4757ULL, 0xaa1c7b6d89f89141ULL, 0xb6e713cdfae0ca3aULL, 0x26694fbb4e82ebc3ULL};
__device__ static const unsigned long long K_NR1P3_A0[4] = {0xe4bbdd0c2936b629ULL, 0xbb30f162e133bacbULL, 0x31a9d1b6f9645366ULL, 0x253570bea500f8ddULL};
__device__ static const unsigned long long K_NR1P3_A1[4] = {0xa1d77ce45ffe77c7ULL, 0x07affd117826d1dbULL, 0x6d16bd27bb7edc6bULL, 0x2c87200285defeccULL};
__device__ static const unsigned long long K_NR1P4_A0[4] = {0x7361d77f843abe92ULL, 0xa5bb2bd3273411fbULL, 0x9c941f314b3e2399ULL, 0x15df9cddbb9fd3ecULL};
__device__ static const unsigned long long K_NR1P4_A1[4] = {0x5dddfd154bd8c949ULL, 0x62cb29a5a4445b60ULL, 0x37bc870a0c7dd2b9ULL, 0x24830a9d3171f0fdULL};
__device__ static const unsigned long long K_NR1P5_A0[4] = {0xc970692f41690fe7ULL, 0xe240342127694b0bULL, 0x32bee66b83c459e8ULL, 0x12aabced0ab08841ULL};
__device__ static const unsigned long long K_NR1P5_A1[4] = {0x0d485d2340aebfa9ULL, 0x05193418ab2fcc57ULL, 0xd3b0a40b8a4910f5ULL, 0x2f21ebb535d2925aULL};

__device__ static const unsigned long long K_NR2P1[4] = {0xca8d800500fa1bf2ULL, 0xf0c5d61468b39769ULL, 0x0e201271ad0d4418ULL, 0x04290f65bad856e6ULL};
__device__ static const unsigned long long K_NR2P2[4] = {0x3350c88e13e80b9cULL, 0x7dce557cdb5e56b9ULL, 0x6001b4b8b615564aULL, 0x2682e617020217e0ULL};
__device__ static const unsigned long long K_NR2P3[4] = {0x68c3488912edefaaULL, 0x8d087f6872aabf4fULL, 0x51e1a24709081231ULL, 0x2259d6b14729c0faULL};
__device__ static const unsigned long long K_NR2P4[4] = {0x71930c11d782e155ULL, 0xa6bb947cffbe3323ULL, 0xaa303344d4741444ULL, 0x2c3b3f0d26594943ULL};
__device__ static const unsigned long long K_NR2P5[4] = {0x08cfc388c494f1abULL, 0x19b315148d1373d4ULL, 0x584e90fdcb6c0213ULL, 0x09e1685bdf2f8849ULL};

__device__ static const unsigned long long K_NR3P1_A0[4] = {0x365316184e46d97dULL, 0x0af7129ed4c96d9fULL, 0x659da72fca1009b5ULL, 0x08116d8983a20d23ULL};
__device__ static const unsigned long long K_NR3P1_A1[4] = {0xb1df4af7c39c1939ULL, 0x3d9f02878a73bf7fULL, 0x9b2220928caf0ae0ULL, 0x26684515eff054a6ULL};
__device__ static const unsigned long long K_NR3P2_A0[4] = {0xc9af22f716ad6badULL, 0xb311782a4aa662b2ULL, 0x19eeaf64e248c7f4ULL, 0x20273e77e3439f82ULL};
__device__ static const unsigned long long K_NR3P2_A1[4] = {0xacc02860f7ce93acULL, 0x3933d5817ba76b4cULL, 0x69e6188b446c8467ULL, 0x0a46036d4417cc55ULL};
__device__ static const unsigned long long K_NR3P3_A0[4] = {0x5764af0aaf46471eULL, 0xdc50792e873e0fc1ULL, 0x86a673ff881d04f6ULL, 0x0b2eddb43c30a74cULL};
__device__ static const unsigned long long K_NR3P3_A1[4] = {0x9a490f32787e8580ULL, 0x8fd16d7ff04af8b1ULL, 0x4b39888ec6027bf2ULL, 0x03dd2e705b52a15dULL};
__device__ static const unsigned long long K_NR3P4_A0[4] = {0x448a93a57b6762dfULL, 0xbfd62df528fdeadfULL, 0xd858f5d00e9bd47aULL, 0x06b03d4d3476ec58ULL};
__device__ static const unsigned long long K_NR3P4_A1[4] = {0x2b19daf4bcc936d1ULL, 0xa1a54e7a56f4299fULL, 0xb533eee05adeaef1ULL, 0x170c812b84dda0b2ULL};
__device__ static const unsigned long long K_NR3P5_A0[4] = {0xe0bc4b2275cf559fULL, 0xc238b945c154e60fULL, 0x803982a5929a7d5eULL, 0x15ce052df7e4a37eULL};
__device__ static const unsigned long long K_NR3P5_A1[4] = {0x2d28efbdbf3799a7ULL, 0x9b097e3c1ad60773ULL, 0x982d4113af4a535bULL, 0x24e18991e3056063ULL};

#endif  // KINET_BN254_PAIRING_CONST_CUH
