// Poseidon2-BN254 KAT against gnark-crypto v0.20.1 (the Go canonical reference
// at github.com/consensys/gnark-crypto/ecc/bn254/fr/poseidon2 with default
// parameters t=2, rF=6, rP=50, d=5).
//
// Vectors generated by tools/gen_kat.go feeding 14 inputs through
//   poseidon2.NewDefaultPermutation().Compress(left, right).
//
// Pass criteria: every Compress(left, right) digest produced by the C++
// implementation matches the Go reference byte-for-byte (32 bytes each, big-
// endian fr.Element encoding).

#include "poseidon.hpp"
#include "kinet_crypto.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>

namespace {

int g_failures = 0;

std::string hex(const std::uint8_t* b, std::size_t n) {
    static const char* H = "0123456789abcdef";
    std::string r;
    r.reserve(n * 2);
    for (std::size_t i = 0; i < n; ++i) {
        r.push_back(H[b[i] >> 4]);
        r.push_back(H[b[i] & 0xF]);
    }
    return r;
}

bool from_hex(const char* s, std::uint8_t* out, std::size_t n) {
    if (std::strlen(s) != n * 2) return false;
    auto nyb = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return 10 + (c - 'a');
        if (c >= 'A' && c <= 'F') return 10 + (c - 'A');
        return -1;
    };
    for (std::size_t i = 0; i < n; ++i) {
        int hi = nyb(s[2 * i]);
        int lo = nyb(s[2 * i + 1]);
        if (hi < 0 || lo < 0) return false;
        out[i] = static_cast<std::uint8_t>((hi << 4) | lo);
    }
    return true;
}

struct Kat {
    const char* name;
    const char* left_be_hex;   // 64 hex chars (32 bytes)
    const char* right_be_hex;  // 64 hex chars (32 bytes)
    const char* expect_be_hex; // 64 hex chars (32 bytes)
};

// Generated by tools/gen_kat.go against gnark-crypto v0.20.1 default Poseidon2.
const Kat kKats[] = {
    {"zero_zero",
     "0000000000000000000000000000000000000000000000000000000000000000",
     "0000000000000000000000000000000000000000000000000000000000000000",
     "292c3a4b9343aec63e584aefa8bedeaefae44e6d718451a75736def795109dfb"},
    {"one_zero",
     "0000000000000000000000000000000000000000000000000000000000000001",
     "0000000000000000000000000000000000000000000000000000000000000000",
     "07cdd5328ddaeedb3415fb6c552975ef1dd225dd1f17db16ca7f859c26fda9e1"},
    {"zero_one",
     "0000000000000000000000000000000000000000000000000000000000000000",
     "0000000000000000000000000000000000000000000000000000000000000001",
     "1ae0efd28c01163c0a58440757ef2339affb17836ad3b1fedacabeaab56ca0e2"},
    {"one_one",
     "0000000000000000000000000000000000000000000000000000000000000001",
     "0000000000000000000000000000000000000000000000000000000000000001",
     "21ca8cd7df3adfa0d4c28b5cca4537df86c62f0c818dd493884b068e3ba9d296"},
    {"two_three",
     "0000000000000000000000000000000000000000000000000000000000000002",
     "0000000000000000000000000000000000000000000000000000000000000003",
     "1541d618b754eaf4234ce26d55097bdea7d0acb4f4671d6f876926d209f1e812"},
    {"alpha_beta",
     "0a0b0c0d0e0f1011121314151617181920212223242526272829303132333435",
     "01b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890abcdef012345",
     "26b587fd47866f0860613efa78a78814b87c345adcaa74c35612e223b46b2140"},
    {"max_minus_one",
     "30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000",
     "0000000000000000000000000000000000000000000000000000000000000001",
     "2b9917f2b9e77cba1ea67bbd4f58bdac187471532cab33b3902fcf1c72ed9863"},
    {"q_minus_one_both",
     "30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000",
     "30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000",
     "0fbef2e10ba2026e48bfdaf86421918320e57e9ae7c387afcd68aa92dba9c2f1"},
    {"interleaved",
     "0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
     "0555555555555555555555555555555555555555555555555555555555555555",
     "18017963ef175fc6a55888ca9367251068ffac8f1ed0d900f89f64a03a4a1077"},
    {"deadbeef_cafebabe",
     "00000000000000000000000000000000000000000000000000000000deadbeef",
     "00000000000000000000000000000000000000000000000000000000cafebabe",
     "16029afd01767ee08f1246ba39012c70ce93535031d12d4dad9b5e5105d0db54"},
    {"high_low",
     "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
     "0edcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
     "29e32fa116ff0922745c4fcd589a9b394a92ba120bf078ed43b7429ae5c5b09f"},
    {"merkle_l0",
     "17b0761f87b081d5cf10757ccc89f12be355c70e2e29df288b65b30710dcbcd1",
     "00ce0a73ad9c8da6c5af0f3aaeebbed5b3c45e92dc6cb24f3a5d8d18d4234d52",
     "0d990f8c5b363f63c940de5bd44e5866a49575dcb0b2c53c5535b9f3e5784283"},
    {"merkle_l1",
     "13b8da37bf68d9c1c19c4f8a4f2e7e3a4b8c5b22b6e1a8b6f5e7c8a3a1c5e6f7",
     "0a000000000000000000000000000000000000000000000000000000000000ff",
     "0071662f7dc1e66a3af54ed7476bc8cee277a2601963bd108a876d29fb7404e5"},
    {"reversed_pair",
     "01b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890abcdef012345",
     "0a0b0c0d0e0f1011121314151617181920212223242526272829303132333435",
     "1c9f286e22de984c3727bbf34a8055b2a16b7af83058c011d45d6da193d97c84"},
};

void check_hash2(const Kat& k) {
    std::uint8_t in[64];
    std::uint8_t want[32];
    if (!from_hex(k.left_be_hex,  in,      32) ||
        !from_hex(k.right_be_hex, in + 32, 32) ||
        !from_hex(k.expect_be_hex, want,   32)) {
        std::fprintf(stderr, "FAIL %s: malformed KAT\n", k.name);
        ++g_failures;
        return;
    }

    // (a) C ABI surface: kinet_poseidon_hash2.
    std::uint8_t got_c[32];
    int rc = kinet_poseidon_hash2(in, got_c);
    if (rc != 0) {
        std::fprintf(stderr, "FAIL %s: kinet_poseidon_hash2 rc=%d\n", k.name, rc);
        ++g_failures;
        return;
    }

    // (b) C++ surface: kinet::crypto::poseidon::hash2 with from_bytes/to_bytes.
    using namespace kinet::crypto::poseidon;
    Bytes32 lbe{}, rbe{};
    std::memcpy(lbe.data(), in, 32);
    std::memcpy(rbe.data(), in + 32, 32);
    Fr l, r;
    if (!from_bytes(lbe, l) || !from_bytes(rbe, r)) {
        std::fprintf(stderr, "FAIL %s: from_bytes rejected canonical input\n", k.name);
        ++g_failures;
        return;
    }
    Fr h = hash2(l, r);
    Bytes32 obe = to_bytes(h);

    bool ok_c   = std::memcmp(got_c,    want, 32) == 0;
    bool ok_cpp = std::memcmp(obe.data(), want, 32) == 0;
    bool ok_eq  = std::memcmp(got_c, obe.data(), 32) == 0;

    if (ok_c && ok_cpp && ok_eq) {
        std::fprintf(stdout, "PASS %s\n", k.name);
    } else {
        std::fprintf(stderr, "FAIL %s\n  want %s\n  c    %s\n  cpp  %s\n",
                     k.name,
                     hex(want, 32).c_str(),
                     hex(got_c, 32).c_str(),
                     hex(obe.data(), 32).c_str());
        ++g_failures;
    }
}

// hash_n via Compress chain: state = 0; for each x_i: state = Compress(state, x_i).
// Vector cross-checked against gnark-crypto NewMerkleDamgardHasher.Sum().
void check_hash_n_chain() {
    // Inputs: 1, 2, 3, 4 each as 32 BE bytes.
    std::uint8_t in[128] = {0};
    in[31]  = 1;
    in[63]  = 2;
    in[95]  = 3;
    in[127] = 4;
    const char* want_hex =
        "0bf1e7d92cff33e808e2a0d0c74e95173cdc92fa02d009b3a015895f8ac13a61";
    std::uint8_t want[32];
    from_hex(want_hex, want, 32);

    // (a) C ABI: kinet_poseidon_hash_n.
    std::uint8_t got_c[32];
    int rc = kinet_poseidon_hash_n(in, sizeof(in), got_c);
    if (rc != 0) {
        std::fprintf(stderr, "FAIL hash_n_chain: kinet_poseidon_hash_n rc=%d\n", rc);
        ++g_failures;
        return;
    }
    // (b) Umbrella: poseidon_bn254 (must dispatch to the same path).
    std::uint8_t got_u[32];
    int ru = poseidon_bn254(in, sizeof(in), got_u);
    if (ru != CRYPTO_OK) {
        std::fprintf(stderr, "FAIL hash_n_chain: poseidon_bn254 rc=%d\n", ru);
        ++g_failures;
        return;
    }
    bool ok = std::memcmp(got_c, want, 32) == 0 &&
              std::memcmp(got_u, want, 32) == 0;
    if (ok) {
        std::fprintf(stdout, "PASS hash_n_chain\n");
    } else {
        std::fprintf(stderr, "FAIL hash_n_chain\n  want %s\n  c    %s\n  umb  %s\n",
                     hex(want, 32).c_str(),
                     hex(got_c, 32).c_str(),
                     hex(got_u, 32).c_str());
        ++g_failures;
    }
}

void check_non_canonical_rejected() {
    // Build an input where the left half encodes q exactly (which is >= q).
    // q = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001.
    std::uint8_t in[64];
    std::memset(in, 0, sizeof(in));
    static const char* q_hex =
        "30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001";
    if (!from_hex(q_hex, in, 32)) {
        std::fprintf(stderr, "FAIL non_canonical_rejected: hex setup\n");
        ++g_failures;
        return;
    }
    std::uint8_t out[32];
    int rc = kinet_poseidon_hash2(in, out);
    if (rc == 0) {
        std::fprintf(stderr,
                     "FAIL non_canonical_rejected: hash2 accepted input == q\n");
        ++g_failures;
    } else {
        std::fprintf(stdout, "PASS non_canonical_rejected (rc=%d)\n", rc);
    }
}

void check_misaligned_hash_n_rejected() {
    std::uint8_t in[33] = {0};
    std::uint8_t out[32];
    int rc = kinet_poseidon_hash_n(in, sizeof(in), out);
    if (rc == 0) {
        std::fprintf(stderr,
                     "FAIL misaligned_hash_n_rejected: accepted in_len=%zu\n",
                     sizeof(in));
        ++g_failures;
    } else {
        std::fprintf(stdout,
                     "PASS misaligned_hash_n_rejected (rc=%d)\n", rc);
    }
}

}  // namespace

int main() {
    std::fprintf(stdout, "=== poseidon2-bn254 KAT vs gnark-crypto v0.20.1 ===\n");

    // 14 KATs.
    for (const Kat& k : kKats) check_hash2(k);
    // hash_n via Merkle-Damgard chain.
    check_hash_n_chain();
    // Negative tests.
    check_non_canonical_rejected();
    check_misaligned_hash_n_rejected();

    if (g_failures == 0) {
        std::fprintf(stdout, "\nALL PASS (%zu KATs + 3 negative tests)\n",
                     sizeof(kKats) / sizeof(kKats[0]));
        return 0;
    }
    std::fprintf(stderr, "\n%d FAIL\n", g_failures);
    return 1;
}
