// pedersen vector-commitment KAT tests.
//
// Coverage:
//   * Generators::from_seed cross-check: all 8 G_i and H byte-equal Go
//     reference (gnark-crypto bn254.HashToG1) for seed = {0,1,...,31}.
//   * 5 commit-verify roundtrips: each commitment byte-equal Go reference,
//     each verify_open returns true on the canonical opening, and false on
//     a single-bit mutation of the commitment.
//
// Fixture file pedersen_kat.h is generated by
// pedersen/test/tools/gen_pedersen_kat.go.

#include "pedersen.hpp"
#include "bn254_fp.hpp"
#include "bn254_g1.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace lc = kinet::crypto::bn254;
namespace lp = kinet::crypto::pedersen;

namespace {

#include "pedersen_kat.h"

int g_pass = 0;
int g_fail = 0;

void check(bool cond, const char* name) {
    if (cond) {
        ++g_pass;
        std::printf("PASS %s\n", name);
    } else {
        ++g_fail;
        std::printf("FAIL %s\n", name);
    }
}

// Decode a 64-character hex string (32 bytes) into a 32-byte buffer.
bool hex_to_be32(const char* hex, uint8_t out[32]) {
    auto nyb = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return 10 + (c - 'a');
        if (c >= 'A' && c <= 'F') return 10 + (c - 'A');
        return -1;
    };
    for (int i = 0; i < 32; ++i) {
        int hi = nyb(hex[2 * i]);
        int lo = nyb(hex[2 * i + 1]);
        if (hi < 0 || lo < 0) return false;
        out[i] = (uint8_t)((hi << 4) | lo);
    }
    return true;
}

// Convert Mont-form Fp -> 32 raw big-endian bytes.
void fp_mont_to_be32(const lc::U256& v, uint8_t out[32]) {
    const lc::U256 raw = lc::from_mont_fp(v);
    raw.to_be32(out);
}

bool be32_eq(const uint8_t a[32], const uint8_t b[32]) {
    for (int i = 0; i < 32; ++i) if (a[i] != b[i]) return false;
    return true;
}

void hex_dump(const uint8_t b[32], char out[65]) {
    static const char* hexd = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        out[2 * i + 0] = hexd[(b[i] >> 4) & 0xF];
        out[2 * i + 1] = hexd[b[i] & 0xF];
    }
    out[64] = 0;
}

void test_generators_from_seed() {
    uint8_t seed[32];
    if (!hex_to_be32(PEDERSEN_KAT_SEED_HEX, seed)) {
        check(false, "seed hex parse");
        return;
    }

    lp::Generators gens;
    bool ok = lp::Generators::from_seed(seed, PEDERSEN_KAT_N, gens);
    check(ok, "Generators::from_seed");
    if (!ok) return;
    check(gens.G_basis.size() == PEDERSEN_KAT_N, "G_basis size == N");

    for (unsigned i = 0; i < PEDERSEN_KAT_N; ++i) {
        uint8_t want_x[32], want_y[32];
        bool ph1 = hex_to_be32(PEDERSEN_KAT_GENS_X_HEX[i], want_x);
        bool ph2 = hex_to_be32(PEDERSEN_KAT_GENS_Y_HEX[i], want_y);
        if (!ph1 || !ph2) {
            check(false, "gens hex parse");
            continue;
        }
        uint8_t got_x[32], got_y[32];
        fp_mont_to_be32(gens.G_basis[i].x, got_x);
        fp_mont_to_be32(gens.G_basis[i].y, got_y);

        char label_x[64], label_y[64];
        std::snprintf(label_x, sizeof(label_x),
                      "G[%u].x byte-equal Go reference", i);
        std::snprintf(label_y, sizeof(label_y),
                      "G[%u].y byte-equal Go reference", i);

        bool ex = be32_eq(got_x, want_x);
        bool ey = be32_eq(got_y, want_y);
        if (!ex) {
            char hg[65], hw[65];
            hex_dump(got_x, hg);
            hex_dump(want_x, hw);
            std::printf("  got_x =%s\n  want_x=%s\n", hg, hw);
        }
        if (!ey) {
            char hg[65], hw[65];
            hex_dump(got_y, hg);
            hex_dump(want_y, hw);
            std::printf("  got_y =%s\n  want_y=%s\n", hg, hw);
        }
        check(ex, label_x);
        check(ey, label_y);
    }

    {
        uint8_t want_x[32], want_y[32];
        bool ph1 = hex_to_be32(PEDERSEN_KAT_H_X_HEX, want_x);
        bool ph2 = hex_to_be32(PEDERSEN_KAT_H_Y_HEX, want_y);
        if (!ph1 || !ph2) {
            check(false, "H hex parse");
        } else {
            uint8_t got_x[32], got_y[32];
            fp_mont_to_be32(gens.H.x, got_x);
            fp_mont_to_be32(gens.H.y, got_y);

            bool ex = be32_eq(got_x, want_x);
            bool ey = be32_eq(got_y, want_y);
            if (!ex) {
                char hg[65], hw[65];
                hex_dump(got_x, hg);
                hex_dump(want_x, hw);
                std::printf("  H.got_x =%s\n  H.want_x=%s\n", hg, hw);
            }
            if (!ey) {
                char hg[65], hw[65];
                hex_dump(got_y, hg);
                hex_dump(want_y, hw);
                std::printf("  H.got_y =%s\n  H.want_y=%s\n", hg, hw);
            }
            check(ex, "H.x byte-equal Go reference");
            check(ey, "H.y byte-equal Go reference");
        }
    }
}

void test_commit_roundtrips() {
    uint8_t seed[32];
    hex_to_be32(PEDERSEN_KAT_SEED_HEX, seed);

    lp::Generators gens;
    bool ok = lp::Generators::from_seed(seed, PEDERSEN_KAT_N, gens);
    if (!ok) {
        check(false, "from_seed for roundtrips");
        return;
    }

    for (unsigned r = 0; r < PEDERSEN_KAT_ROUNDS; ++r) {
        const auto& kat = PEDERSEN_KAT_ROUNDTRIPS[r];

        std::vector<lc::U256> scalars(PEDERSEN_KAT_N);
        for (unsigned i = 0; i < PEDERSEN_KAT_N; ++i) {
            uint8_t b[32];
            hex_to_be32(kat.scalars_hex[i], b);
            // Scalars are already reduced mod r in the Go reference.
            scalars[i] = lc::U256::from_be32(b);
        }
        lc::U256 blinding;
        {
            uint8_t b[32];
            hex_to_be32(kat.blinding_hex, b);
            blinding = lc::U256::from_be32(b);
        }

        const lc::G1Affine c = lp::commit(
            std::span<const lc::U256>{scalars.data(), scalars.size()},
            blinding, gens);

        // Compare commitment to Go reference, byte-by-byte.
        uint8_t got_x[32], got_y[32];
        fp_mont_to_be32(c.x, got_x);
        fp_mont_to_be32(c.y, got_y);
        uint8_t want_x[32], want_y[32];
        hex_to_be32(kat.commitment_x_hex, want_x);
        hex_to_be32(kat.commitment_y_hex, want_y);

        char label[64];
        std::snprintf(label, sizeof(label),
                      "round[%u]: commitment.x byte-equal Go", r);
        bool ex = be32_eq(got_x, want_x);
        if (!ex) {
            char hg[65], hw[65];
            hex_dump(got_x, hg);
            hex_dump(want_x, hw);
            std::printf("  got_x =%s\n  want_x=%s\n", hg, hw);
        }
        check(ex, label);
        std::snprintf(label, sizeof(label),
                      "round[%u]: commitment.y byte-equal Go", r);
        bool ey = be32_eq(got_y, want_y);
        if (!ey) {
            char hg[65], hw[65];
            hex_dump(got_y, hg);
            hex_dump(want_y, hw);
            std::printf("  got_y =%s\n  want_y=%s\n", hg, hw);
        }
        check(ey, label);

        // Round-trip verify_open: must accept the canonical opening.
        bool v = lp::verify_open(
            c, std::span<const lc::U256>{scalars.data(), scalars.size()},
            blinding, gens);
        std::snprintf(label, sizeof(label),
                      "round[%u]: verify_open(canonical) == true", r);
        check(v, label);

        // Negative test: flipping a single bit of any scalar must reject.
        {
            std::vector<lc::U256> mutated = scalars;
            mutated[0].limbs[0] ^= 0x1ULL;
            bool vneg = lp::verify_open(
                c,
                std::span<const lc::U256>{mutated.data(), mutated.size()},
                blinding, gens);
            std::snprintf(label, sizeof(label),
                          "round[%u]: verify_open(mutated scalar) == false", r);
            check(!vneg, label);
        }

        // Negative test: flipping the blinding rejects.
        {
            lc::U256 mutated_blinding = blinding;
            mutated_blinding.limbs[0] ^= 0x1ULL;
            bool vneg = lp::verify_open(
                c,
                std::span<const lc::U256>{scalars.data(), scalars.size()},
                mutated_blinding, gens);
            std::snprintf(label, sizeof(label),
                          "round[%u]: verify_open(mutated blinding) == false", r);
            check(!vneg, label);
        }
    }
}

}  // namespace

int main() {
    test_generators_from_seed();
    test_commit_roundtrips();
    std::printf("=== %d passed, %d failed ===\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
