// SPDX-License-Identifier: Apache-2.0
//
// gen_ipa_kat.go -- emit IPA KAT vectors for the C++ implementation in
// kinet-labs/crypto/ipa. Source of truth is github.com/kinet-labs/crypto/ipa.
//
// Usage:
//   cd /Users/z/work/kinet-labs/crypto-ipa-wt/ipa/test/tools
//   go run gen_ipa_kat.go > ../ipa_kat.h
//
// Produces:
//   - 5 valid prover/verifier KAT roundtrips at N=256 (in-domain + out-of-
//     domain mix); records (poly[256], eval, commitment, y, proof[544]).
//   - 3 negative-test vectors (wrong commitment, wrong y, tampered proof).
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/kinet-labs/crypto/ipa/bandersnatch/fr"
	"github.com/kinet-labs/crypto/ipa/common"
	"github.com/kinet-labs/crypto/ipa/ipa"
)

type detRng struct{ s uint64 }

func newDetRng(seed uint64) *detRng { return &detRng{s: seed} }
func (r *detRng) next() uint64 {
	x := r.s
	x ^= x << 13
	x ^= x >> 7
	x ^= x << 17
	r.s = x
	return x * 2685821657736338717
}

func cBytesN(b []byte) string {
	out := ""
	for i, x := range b {
		if i > 0 {
			out += ", "
		}
		if i > 0 && i%12 == 0 {
			out += "\n     "
		}
		out += fmt.Sprintf("0x%02x", x)
	}
	return out
}

func deterministicPoly(seed uint64) []fr.Element {
	r := newDetRng(seed)
	poly := make([]fr.Element, common.VectorLength)
	for i := range poly {
		var buf [32]byte
		for k := 0; k < 4; k++ {
			v := r.next()
			for b := 0; b < 8; b++ {
				buf[8*k+b] = byte(v >> (8 * b))
			}
		}
		buf[31] &= 0x07
		_, err := poly[i].SetBytesLECanonical(buf[:])
		if err != nil {
			poly[i].SetUint64(uint64(i + 1))
		}
	}
	return poly
}

func main() {
	out := os.Stdout

	cfg, err := ipa.NewIPASettings()
	if err != nil {
		fmt.Fprintf(os.Stderr, "NewIPASettings: %v\n", err)
		os.Exit(1)
	}

	type validKat struct {
		name     string
		polyLE   []byte
		evalLE   [32]byte
		commitBE [32]byte
		yLE      [32]byte
		proofBE  []byte
	}

	var valid []validKat

	specs := []struct {
		name string
		seed uint64
		eval uint64
	}{
		{"in_domain_0", 1, 0},
		{"in_domain_42", 2, 42},
		{"in_domain_255", 3, 255},
		{"out_of_domain_2101", 4, 2101},
		{"out_of_domain_big", 5, 123456789},
	}

	for _, sp := range specs {
		poly := deterministicPoly(sp.seed)
		var evalPoint fr.Element
		evalPoint.SetUint64(sp.eval)

		commit := cfg.Commit(poly)

		polyLE := make([]byte, 256*32)
		for i, e := range poly {
			b := e.BytesLE()
			copy(polyLE[i*32:(i+1)*32], b[:])
		}
		evalLE := evalPoint.BytesLE()
		commitBE := commit.Bytes()

		transcript := common.NewTranscript("ipa")
		proof, err := ipa.CreateIPAProof(transcript, cfg, commit, poly, evalPoint)
		if err != nil {
			fmt.Fprintf(os.Stderr, "create_proof %s: %v\n", sp.name, err)
			os.Exit(1)
		}

		var lagrange []fr.Element
		if sp.eval < uint64(common.VectorLength) {
			lagrange = make([]fr.Element, common.VectorLength)
			lagrange[sp.eval] = fr.One()
		} else {
			lagrange = cfg.PrecomputedWeights.ComputeBarycentricCoefficients(evalPoint)
		}
		y, err := ipa.InnerProd(poly, lagrange)
		if err != nil {
			fmt.Fprintf(os.Stderr, "inner_prod %s: %v\n", sp.name, err)
			os.Exit(1)
		}
		yLE := y.BytesLE()

		buf := new(bytes.Buffer)
		if err := proof.Write(buf); err != nil {
			fmt.Fprintf(os.Stderr, "proof.Write %s: %v\n", sp.name, err)
			os.Exit(1)
		}
		proofBE := buf.Bytes()
		if len(proofBE) != 544 {
			fmt.Fprintf(os.Stderr, "proof size %d != 544\n", len(proofBE))
			os.Exit(1)
		}

		vt := common.NewTranscript("ipa")
		ok, err := ipa.CheckIPAProof(vt, cfg, commit, proof, evalPoint, y)
		if err != nil || !ok {
			fmt.Fprintf(os.Stderr, "check_proof %s: ok=%v err=%v\n", sp.name, ok, err)
			os.Exit(1)
		}

		valid = append(valid, validKat{
			name:     sp.name,
			polyLE:   polyLE,
			evalLE:   evalLE,
			commitBE: commitBE,
			yLE:      yLE,
			proofBE:  proofBE,
		})
	}

	type negKat struct {
		name     string
		commitBE [32]byte
		evalLE   [32]byte
		yLE      [32]byte
		proofBE  []byte
	}
	var neg []negKat
	neg = append(neg, negKat{
		name:     "wrong_commitment",
		commitBE: valid[1].commitBE,
		evalLE:   valid[0].evalLE,
		yLE:      valid[0].yLE,
		proofBE:  append([]byte(nil), valid[0].proofBE...),
	})
	neg = append(neg, negKat{
		name:     "wrong_y",
		commitBE: valid[0].commitBE,
		evalLE:   valid[0].evalLE,
		yLE:      valid[1].yLE,
		proofBE:  append([]byte(nil), valid[0].proofBE...),
	})
	tampered := append([]byte(nil), valid[0].proofBE...)
	tampered[100] ^= 0x01
	neg = append(neg, negKat{
		name:     "tampered_proof",
		commitBE: valid[0].commitBE,
		evalLE:   valid[0].evalLE,
		yLE:      valid[0].yLE,
		proofBE:  tampered,
	})

	fmt.Fprintln(out, "// SPDX-License-Identifier: Apache-2.0")
	fmt.Fprintln(out, "// ipa_kat.h -- generated by ipa/test/tools/gen_ipa_kat.go")
	fmt.Fprintln(out, "// Source of truth: github.com/kinet-labs/crypto/ipa")
	fmt.Fprintln(out, "// DO NOT EDIT.")
	fmt.Fprintln(out, "#pragma once")
	fmt.Fprintln(out, "#include <cstdint>")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "namespace kinet::crypto::ipa::kat {")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "struct IPAValidKat {")
	fmt.Fprintln(out, "    const char* name;")
	fmt.Fprintln(out, "    std::uint8_t poly_le[256 * 32];")
	fmt.Fprintln(out, "    std::uint8_t eval_le[32];")
	fmt.Fprintln(out, "    std::uint8_t commit_be[32];")
	fmt.Fprintln(out, "    std::uint8_t y_le[32];")
	fmt.Fprintln(out, "    std::uint8_t proof[544];")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "struct IPANegKat {")
	fmt.Fprintln(out, "    const char* name;")
	fmt.Fprintln(out, "    std::uint8_t commit_be[32];")
	fmt.Fprintln(out, "    std::uint8_t eval_le[32];")
	fmt.Fprintln(out, "    std::uint8_t y_le[32];")
	fmt.Fprintln(out, "    std::uint8_t proof[544];")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintf(out, "constexpr int kIPAValidKatCount = %d;\n", len(valid))
	fmt.Fprintf(out, "constexpr int kIPANegKatCount   = %d;\n", len(neg))
	fmt.Fprintln(out, "")

	fmt.Fprintln(out, "inline const IPAValidKat kIPAValidKats[] = {")
	for _, k := range valid {
		fmt.Fprintf(out, "    {\"%s\",\n", k.name)
		fmt.Fprintf(out, "     /*poly_le=*/{%s},\n", cBytesN(k.polyLE))
		fmt.Fprintf(out, "     /*eval_le=*/{%s},\n", cBytesN(k.evalLE[:]))
		fmt.Fprintf(out, "     /*commit_be=*/{%s},\n", cBytesN(k.commitBE[:]))
		fmt.Fprintf(out, "     /*y_le=*/{%s},\n", cBytesN(k.yLE[:]))
		fmt.Fprintf(out, "     /*proof=*/{%s}},\n", cBytesN(k.proofBE))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")

	fmt.Fprintln(out, "inline const IPANegKat kIPANegKats[] = {")
	for _, k := range neg {
		fmt.Fprintf(out, "    {\"%s\",\n", k.name)
		fmt.Fprintf(out, "     /*commit_be=*/{%s},\n", cBytesN(k.commitBE[:]))
		fmt.Fprintf(out, "     /*eval_le=*/{%s},\n", cBytesN(k.evalLE[:]))
		fmt.Fprintf(out, "     /*y_le=*/{%s},\n", cBytesN(k.yLE[:]))
		fmt.Fprintf(out, "     /*proof=*/{%s}},\n", cBytesN(k.proofBE))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "}  // namespace kinet::crypto::ipa::kat")
}
